input-output-hk/plutus-apps

- plutus-playground-client/src/MainFrame/Lenses.purs
- plutus-playground-client/src/MainFrame/State.purs
- plutus-playground-client/src/MainFrame/Types.purs
> SCP-1751: Keep simulation state after compilation error

- plutus-pab-client/src/MonadApp.purs
> Fix display of contracts on activation

- plutus-chain-index/src/Plutus/ChainIndex/App.hs
#68 was lost in the last merge :(
- Branch
- PR
> Re: Chain index app: query the tip of the node for first response before start

- plutus-ledger/src/Ledger/Constraints.hs
> Export mustSatisfyAnyOf in Ledger.Constraints (fix #95).

- plutus-contract/src/Plutus/Contract/Test/ContractModel.hs
- plutus-use-cases/src/Plutus/Contracts/Crowdfunding.hs
- plutus-use-cases/test/Spec/Crowdfunding.hs
- plutus-use-cases/test/Spec/Escrow.hs
- plutus-use-cases/test/Spec/GameStateMachine.hs
This PR introduces some more `ContractModel` models for example contracts
and improves the error whitelist checking interface.
- Branch
- PR
> Plutus-use-cases QuickCheck models

- plutus-pab/test-node/README.md
- plutus-pab/test-node/start-testnet-node.sh
> Upgrade node version

- plutus-chain-index-core/src/Plutus/ChainIndex/DbSchema.hs
- plutus-chain-index-core/src/Plutus/ChainIndex/Handlers.hs
This PR attempts to resolve #70. I set this as a draft for further testing. I really feel like missing something and no failed tests make it even more worrying.
- Branch
- PR
> Chain Index: separate scripts and redeemers tables

- CONTRIBUTING.adoc
- cabal.project
> Add contributing section about working with local copies of deps

- plutus-contract/src/Plutus/Contract/Test/ContractModel.hs
- plutus-use-cases/test/Spec/GameStateMachine.hs
Checking that balances sometimes change.
- Branch
- PR
> Contract model sanity check property

- doc/plutus-doc.cabal
- freer-extras/freer-extras.cabal
- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-pab.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-pab.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-pab.nix
- plutus-chain-index-core/plutus-chain-index-core.cabal
- plutus-chain-index/plutus-chain-index.cabal
- plutus-contract/plutus-contract.cabal
- plutus-ledger-constraints/plutus-ledger-constraints.cabal
- plutus-ledger/plutus-ledger.cabal
- plutus-pab/plutus-pab.cabal
- plutus-playground-server/plutus-playground-server.cabal
- plutus-use-cases/plutus-use-cases.cabal
- quickcheck-dynamic/quickcheck-dynamic.cabal
- web-ghc/web-ghc.cabal
> Fix source-repository locations

- plutus-contract/src/Plutus/Contract/Trace.hs
- plutus-contract/src/Wallet/Emulator/Types.hs
- plutus-contract/src/Wallet/Emulator/Wallet.hs
Fixes #104.
Added `walletPubKey` function and updated the original `walletPubKeyHash` function to use this function.
- Branch
- PR
> Add walletPubKey

- plutus-contract/src/Wallet/Emulator/Wallet.hs
> fix broken build

- plutus-chain-index/src/Plutus/ChainIndex/App.hs
> SCP-3001: Show chain index syncing progress

- plutus-playground-client/src/Action/View.purs
- plutus-playground-client/src/Cursor.purs
- plutus-playground-client/src/MainFrame/Lenses.purs
- plutus-playground-client/src/MainFrame/State.purs
- plutus-playground-client/src/MainFrame/Types.purs
- plutus-playground-client/src/MainFrame/View.purs
- plutus-playground-client/src/Simulator/View.purs
Also removed the release banner and renamed Blocks to Slots in the Wait For action.
- Branch
- PR
> Store evaluation with its simulation

- plutus-contract/src/Plutus/Contract/StateMachine/ThreadToken.hs
> Add Ord instance for ThreadToken (fix #157).

- .github/ISSUE_TEMPLATE/bug_report.md
> what-have-you-tried

- plutus-ledger/src/Ledger/Tx/CardanoAPI.hs
- plutus-ledger/src/Ledger/Tx/CardanoAPITemp.hs
> Fix missing datums for toCardanoTxBody

- plutus-use-cases/src/Plutus/Contracts/Uniswap/OnChain.hs
> [plutus-use-cases]: fix Coin type in uniswap (fix #169).

- plutus-contract/test/Spec/Contract.hs
- plutus-ledger-constraints/src/Ledger/Constraints.hs
- plutus-ledger-constraints/src/Ledger/Constraints/OffChain.hs
- plutus-ledger-constraints/src/Ledger/Constraints/OnChain.hs
- plutus-ledger-constraints/src/Ledger/Constraints/TxConstraints.hs
- plutus-use-cases/test/Spec/future.pir
- plutus-use-cases/test/Spec/gameStateMachine.pir
- plutus-use-cases/test/Spec/governance.pir
- plutus-use-cases/test/Spec/multisigStateMachine.pir
- plutus-use-cases/test/Spec/renderGuess.txt
Should fix #146.
---
- Branch
- PR
> Add mustPayWithDatumToPubKey (fix #146).

- plutus-contract/test/Spec/Contract.hs
- plutus-ledger-constraints/src/Ledger/Constraints/OffChain.hs
- plutus-ledger-constraints/src/Ledger/Constraints/OnChain.hs
- plutus-ledger-constraints/src/Ledger/Constraints/TxConstraints.hs
- plutus-use-cases/test/Spec/future.pir
- plutus-use-cases/test/Spec/gameStateMachine.pir
- plutus-use-cases/test/Spec/governance.pir
- plutus-use-cases/test/Spec/multisigStateMachine.pir
- plutus-use-cases/test/Spec/renderGuess.txt
> Fix mustSatisfyAnyOf logic (fix #101).

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/security_report.yml
> Update issue forms. Added security issue form.

- doc/plutus/tutorials/contract-testing.rst
> Fix some hsobj references

- plutus-pab/README.md
As @james-iohk pointed out, the commands in the plutus-pab README were out of date. This PR updates them.
- Branch
- PR
> Update the commands in the plutus-pab README.md

- doc/reference/examples.rst
> repo name fixup

- plutus-pab-executables/demo/pab-nami/README.md
Fix errors introduced from recent folder reorg.
- PR
> Fix errors introduced from previous refactor/reorganisation

- plutus-contract/README.md
> Update plutus-contract README

- flake.lock
- flake.nix
- nix/pkgs/haskell/hls-darwin.sha
- nix/pkgs/haskell/hls-linux.sha
fix #209 
I got a bit different sha as well as in #211. I guess it's fine. The old ones differ as well.
---
- Branch
- PR
> Bump hls to 1.5.1 #209

- plutus-pab-executables/test/full/Plutus/PAB/CliSpec.hs
- plutus-pab-executables/tx-inject/Main.hs
- plutus-pab/src/Cardano/Node/API.hs
- plutus-pab/src/Cardano/Node/Client.hs
- plutus-pab/src/Cardano/Node/Mock.hs
- plutus-pab/src/Cardano/Node/Server.hs
- plutus-pab/src/Cardano/Node/Types.hs
- plutus-pab/src/Cardano/Protocol/Socket/Mock/Server.hs
- plutus-pab/src/Cardano/Wallet/LocalClient.hs
- plutus-pab/src/Cardano/Wallet/RemoteClient.hs
- plutus-pab/src/Plutus/PAB/App.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance/BlockchainEnv.hs
- plutus-pab/src/Plutus/PAB/LocalCluster/Run.hs
- plutus-pab/src/Plutus/PAB/Monitoring/PABLogMsg.hs
- plutus-pab/src/Plutus/PAB/Run.hs
- plutus-pab/src/Plutus/PAB/Run/Cli.hs
- plutus-pab/src/Plutus/PAB/Run/Command.hs
- plutus-pab/src/Plutus/PAB/Run/CommandParser.hs
- plutus-pab/src/Plutus/PAB/Types.hs
Partial fix of sync errors and refactoring.
When starting the PAB using the real node there is no point in starting
the additional mocked services with it.
The following renames have been made:
* StartMockNode to StartPABNode
* MockServerLogMsg to PABServerLogMsg
* (logging message) StartingMockServer to StartingPABServer
* MockServerConfig to PABServerConfig (initially it was just the mock
node config, but since then we've added some specific PAB settings and the
possibility of connecting to a real node).
- Branch
- PR
> Fix synchronisation errors.

- shell.nix
#213 only guarantees stability and build time for `cardano-node` executables so this PR does the same for `cardano-wallet`. It also adds the needed comments.
Also simplifies #214 to make it easier to review (once finalized) and all. 
- Branch
- PR
> shell-nix: also fetch cardano-wallet with more comments

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-chain-index.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-chain-index.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-chain-index.nix
- plutus-chain-index/plutus-chain-index.cabal
- plutus-pab/src/Plutus/PAB/Core/ContractInstance/BlockchainEnv.hs
fix #206
tested against the repo with a provided reproduction case from the issue
---
- Branch
- PR
> Update instances while processing blocks from alonzo node (fix #206)

- README.adoc
- doc/reference/index.rst
> Add links to Haddocks and the playground

- playground-common/src/Schema.hs
> Add ToArgument instance for Slot #271

- plutus-pab-executables/demo/pab-nami/pab/plutus-pab.yaml
* `msc -> psc`
* add `developmentOptions`
Side note: demo only works with `Nami 2.3.6` not the more recent versions - will try to update it.
- Branch
- PR
> Update pab-nami PAB config

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-contract.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-contract.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-contract.nix
- plutus-contract/plutus-contract.cabal
- plutus-contract/src/Wallet/Emulator/Wallet.hs
- plutus-contract/test/Spec.hs
- plutus-contract/test/Spec/Balancing.hs
- plutus-contract/test/Spec/Contract.hs
> Minting doesn't need special treatment after all

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-pab.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-pab.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-pab.nix
- plutus-pab/plutus-pab.cabal
- plutus-pab/src/Plutus/PAB/Core/ContractInstance/BlockchainEnv.hs
The way it was configured rarely if ever prints anything.
- Branch
- PR
> Make the PAB log ~1/10_000 messages.

- doc/plutus/tutorials/GameModel.hs
- plutus-contract/src/Plutus/Contract/Test/ContractModel.hs
- plutus-contract/src/Plutus/Contract/Test/ContractModel/CrashTolerance.hs
- plutus-contract/src/Plutus/Contract/Test/ContractModel/Internal.hs
- plutus-contract/test/Spec/ErrorChecking.hs
- plutus-use-cases/test/Spec/Auction.hs
- plutus-use-cases/test/Spec/Crowdfunding.hs
- plutus-use-cases/test/Spec/Escrow.hs
- plutus-use-cases/test/Spec/GameStateMachine.hs
- plutus-use-cases/test/Spec/Prism.hs
- plutus-use-cases/test/Spec/SealedBidAuction.hs
- plutus-use-cases/test/Spec/Uniswap.hs
- plutus-use-cases/test/Spec/Vesting.hs
This fixes the previous uncomfortable interface to starting contracts in ContractModel tests.
- Branch
- PR
> ContractModel: simplify starting contracts with parameters

- plutus-pab/src/Cardano/Wallet/Mock/API.hs
- plutus-pab/src/Cardano/Wallet/Mock/Client.hs
- plutus-pab/src/Cardano/Wallet/Mock/Handlers.hs
- plutus-pab/src/Cardano/Wallet/Mock/Server.hs
- plutus-pab/src/Cardano/Wallet/Mock/Types.hs
- plutus-pab/src/Plutus/PAB/Simulator.hs
Should fix #17.
----
- Branch
- PR
> Allow to create a new wallet with the provided funds (#17).

- plutus-pab/src/Plutus/PAB/Core/ContractInstance/BlockchainEnv.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance/STM.hs
- plutus-pab/src/Plutus/PAB/Simulator.hs
> Use slotConfig from the config for awaitTime

- plutus-pab/src/Plutus/PAB/Effects/Contract/Builtin.hs
Errors include uses of `throwError` inside a `Contract` and when decoding endpoint parameters.
Here are a few examples.
When a `throwError` is called in the `Contract` Monad:
```
[pab:Info:183] [2022-02-04 00:12:31.10 UTC] Initialising contract PayToWallet with ID 5822163d-4ed9-4b1d-84ba-742855fb4baa
[pab:Info:183] [2022-02-04 00:12:31.11 UTC] Activated instance 5822163d-4ed9-4b1d-84ba-742855fb4baa on W872cb83
[pab:Info:185] [2022-02-04 00:12:31.14 UTC] 5822163d-4ed9-4b1d-84ba-742855fb4baa: "Calling PayToWallet endpoint"
[pab:Error:185] [2022-02-04 00:12:31.14 UTC] 5822163d-4ed9-4b1d-84ba-742855fb4baa: {
"contents": "THIS IS AN ERROR",
"tag": "OtherError"
}
```
When the endpoint parameters could not be decoded (wrong JSON format):
```
[pab:Info:158] [2022-02-04 00:15:14.83 UTC] …
```
> SCP-2985: Contract errors are now logged when running the PAB.

- plutus-pab/src/Cardano/Wallet/LocalClient.hs
- plutus-pab/src/Plutus/PAB/App.hs
fix #285 
Not sure how to test it properly. Copied lines from Mock Wallet.
----
- Branch
- PR
> Update SlotConfig in UnbalancedTx in local wallet client #285

- plutus-pab/src/Plutus/PAB/Core/ContractInstance/BlockchainEnv.hs
The cause of the rollback failure was that `Plutus.ChainIndex.UtxoState.rollbackWith` computes the current tip of the index as the slot of the last transaction, ignoring the fact that there may be empty blocks after that. When a rollback with a target falls within such a sequence of empty blocks, the `rollbackWith` function misinterprets this as a `TipMismatch`.
This change simply checks to see if the rollback is unnecessary because it is
through a sequence of empty blocks ending at the former tip.
This was manually tested on the private Marlowe testnet, where we verified that rollback failures no long occur when they just rollback through empty blocks.
- Branch
- PR
> SCP-3343 fixed intermittent rollback failures in PAB

- deployment.nix
- plutus-pab-executables/pab-cli/README.md
- shell.nix
* The Nix shell should not provide local packages.
* Created a deployment.nix.
- Branch
- PR
> Removed pab-cli and plutus-chain-index from the shell.

- shell.nix
> Add missing plantuml executable when building docs with sphynx.

- plutus-chain-index-core/src/Plutus/ChainIndex/Api.hs
- plutus-chain-index-core/src/Plutus/ChainIndex/Client.hs
- plutus-chain-index-core/src/Plutus/ChainIndex/DbSchema.hs
- plutus-chain-index-core/src/Plutus/ChainIndex/Effects.hs
- plutus-chain-index-core/src/Plutus/ChainIndex/Emulator/DiskState.hs
- plutus-chain-index-core/src/Plutus/ChainIndex/Emulator/Handlers.hs
- plutus-chain-index-core/src/Plutus/ChainIndex/Handlers.hs
- plutus-chain-index-core/src/Plutus/ChainIndex/Server.hs
- plutus-chain-index-core/src/Plutus/ChainIndex/Types.hs
- plutus-chain-index-core/test/Plutus/ChainIndex/Emulator/HandlersSpec.hs
- plutus-chain-index-core/test/Plutus/ChainIndex/HandlersSpec.hs
- plutus-contract/src/Plutus/Contract.hs
- plutus-contract/src/Plutus/Contract/Effects.hs
- plutus-contract/src/Plutus/Contract/Request.hs
- plutus-contract/src/Plutus/Contract/StateMachine.hs
- plutus-contract/src/Plutus/Contract/Trace/RequestHandler.hs
- plutus-contract/src/Wallet/Emulator/Wallet.hs
- plutus-contract/test/Spec/Contract.hs
- plutus-pab-executables/demo/pab-nami/client/generated/Plutus/Contract/Effects.purs
- plutus-pab/src/Plutus/PAB/Core.hs
- plutus-pab/src/Plutus/PAB/Simulator.hs
- plutus-playground-client/generated/Plutus/Contract/Effects.purs
- plutus-use-cases/src/Plutus/Contracts/Auction.hs
- plutus-use-cases/src/Plutus/Contracts/PubKey.hs
> SCP-3501: Remove txs from chain index

- plutus-contract/src/Plutus/Contract/Test.hs
- plutus-contract/src/Plutus/Contract/Test/ContractModel.hs
- plutus-contract/src/Plutus/Contract/Test/ContractModel/Internal.hs
- plutus-contract/src/Plutus/Contract/Test/Coverage.hs
- plutus-contract/test/Spec/Emulator.hs
- plutus-use-cases/test/Spec/GameStateMachine.hs
- plutus-use-cases/test/Spec/Uniswap.hs
This just adds a bit of functionality for collecting and displaying coverage information from unit tests.
- Branch
- PR
> Collect coverage information from on-chain code in unit tests

- plutus-pab/src/Cardano/Node/Types.hs
- plutus-pab/src/Plutus/PAB/Monitoring/PABLogMsg.hs
- plutus-pab/src/Plutus/PAB/Run.hs
- plutus-pab/src/Plutus/PAB/Run/Cli.hs
> Print error message when passing a non-existant socket path in the PAB

- playground-common/src/Schema.hs
- plutus-contract/src/Plutus/Contract/Test.hs
- plutus-contract/src/Plutus/Contract/Test/ContractModel/Internal.hs
- plutus-contract/src/Plutus/Trace/Emulator/System.hs
- plutus-contract/src/Wallet/Emulator/Wallet.hs
- plutus-contract/src/Wallet/Rollup/Render.hs
- plutus-contract/test/Spec/ErrorChecking.hs
- plutus-contract/test/Spec/golden/traceOutput - pubKeyTransactions.txt
- plutus-contract/test/Spec/golden/traceOutput - pubKeyTransactions2.txt
- plutus-contract/test/Spec/golden/traceOutput - wait1.txt
- plutus-ledger/src/Ledger/CardanoWallet.hs
- plutus-pab-executables/demo/pab-nami/client/generated/Wallet/Emulator/Wallet.purs
- plutus-pab/src/Cardano/Wallet/LocalClient.hs
- plutus-pab/src/Cardano/Wallet/Mock/Client.hs
- plutus-pab/src/Cardano/Wallet/Mock/Handlers.hs
- plutus-pab/src/Cardano/Wallet/Mock/Server.hs
- plutus-pab/src/Cardano/Wallet/Mock/Types.hs
- plutus-pab/src/Plutus/PAB/Db/Beam/ContractStore.hs
- plutus-pab/src/Plutus/PAB/Simulator.hs
- plutus-pab/src/Plutus/PAB/Webserver/Handler.hs
- plutus-playground-client/generated/Wallet/Emulator/Wallet.purs
- plutus-playground-client/generated/evaluation_response0.json
- plutus-use-cases/test/Spec/Prism.hs
- plutus-use-cases/test/Spec/Uniswap.hs
- plutus-use-cases/test/Spec/contractError.txt
- plutus-use-cases/test/Spec/crowdfundingEmulatorTestOutput.txt
- plutus-use-cases/test/Spec/crowdfundingWallet1TestOutput.txt
And improve how we show mock wallets in the emulator.
- Branch
- PR
> ContractModel: Test that slot numbers line up between model and emulator

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-pab.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-pab.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-pab.nix
- plutus-contract/src/Plutus/Contract/Wallet.hs
- plutus-contract/src/Plutus/Trace/Emulator/Extract.hs
- plutus-contract/src/Wallet/Emulator/Wallet.hs
- plutus-ledger/src/Ledger/Tx/CardanoAPI.hs
- plutus-pab/plutus-pab.cabal
- plutus-pab/src/Cardano/Wallet/LocalClient.hs
- plutus-pab/src/Cardano/Wallet/RemoteClient.hs
- plutus-pab/test/light/Cardano/Wallet/RemoteClientSpec.hs
A complete fix for https://github.com/input-output-hk/plutus-apps/issues/285.
https://github.com/input-output-hk/plutus-apps/pull/304 partially fixed it for `LocalClient`, but this extends to `RemoteClient` and removes some code duplications as well.
---
- Branch
- PR
> Write validityTimeRange for exported transactions

- plutus-contract/src/Plutus/Contract/Test/ContractModel/Internal.hs
> ContractModel: Improved error message when using an unregistered symbolic token (fix #337)

- plutus-pab-executables/pab-cli/README.md
> Update pab-cli readme nix-shell cmd

- plutus-contract/src/Plutus/Contract/StateMachine.hs
- plutus-contract/src/Plutus/Contract/StateMachine/OnChain.hs
- plutus-ledger-constraints/src/Ledger/Constraints.hs
- plutus-ledger-constraints/src/Ledger/Constraints/OffChain.hs
- plutus-ledger-constraints/src/Ledger/Constraints/OnChain.hs
- plutus-ledger-constraints/src/Ledger/Constraints/TxConstraints.hs
- plutus-ledger/src/Ledger/Tx.hs
- plutus-use-cases/src/Plutus/Contracts/Uniswap/OnChain.hs
- plutus-use-cases/test/Spec/future.pir
- plutus-use-cases/test/Spec/gameStateMachine.pir
- plutus-use-cases/test/Spec/governance.pir
- plutus-use-cases/test/Spec/multisigStateMachine.pir
> SCP-3617: Added Haddock documentation to the constraints in plutus-ledger-constraints

- plutus-chain-index/src/Plutus/ChainIndex/App.hs
> [chain-index]: fix the problem with not starting web server

- plutus-pab-executables/demo/pab-nami/README.md
Remove remnants, make small edits, add Cardano Node instructions for PAB, clarify frontend instructions to include `nix-shell`
> Edit PAB-Nami Demo README

- freer-extras/src/Control/Monad/Freer/Extras/Beam.hs
- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-chain-index.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-chain-index.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-chain-index.nix
- plutus-chain-index-core/src/Plutus/ChainIndex/DbSchema.hs
- plutus-chain-index-core/src/Plutus/ChainIndex/Effects.hs
- plutus-chain-index-core/src/Plutus/ChainIndex/Emulator/Handlers.hs
- plutus-chain-index-core/src/Plutus/ChainIndex/Handlers.hs
- plutus-chain-index-core/test/Plutus/ChainIndex/Emulator/HandlersSpec.hs
- plutus-chain-index-core/test/Plutus/ChainIndex/HandlersSpec.hs
- plutus-chain-index/plutus-chain-index.cabal
- plutus-chain-index/src/Plutus/ChainIndex/App.hs
- plutus-chain-index/src/Plutus/ChainIndex/CommandLine.hs
- plutus-chain-index/src/Plutus/ChainIndex/Config.hs
- plutus-chain-index/src/Plutus/ChainIndex/Events.hs
- plutus-chain-index/src/Plutus/ChainIndex/Lib.hs
- plutus-chain-index/src/Plutus/ChainIndex/SyncStats.hs
- plutus-contract/src/Plutus/Trace/Emulator/System.hs
This should increase the speed of the chain index.
The PR also adds two new config parameters:
- `appendPeriod` — How often the appending of blocks should happen (in microseconds)
- `appendBatchSize` — The number of blocks to collect before writing to the database 
---
- Branch
- PR
> SCP-3502: Add AppendBlocks effect

- cabal.project
- flake.nix
- nix/pkgs/haskell/haskell.nix
- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-contract-certification.nix
- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-use-cases.nix
- nix/pkgs/haskell/materialized-darwin/default.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-contract-certification.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-use-cases.nix
- nix/pkgs/haskell/materialized-linux/default.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-contract-certification.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-use-cases.nix
- nix/pkgs/haskell/materialized-windows/default.nix
- plutus-contract-certification/ARCHITECTURE.adoc
- plutus-contract-certification/LICENSE
- plutus-contract-certification/NOTICE
- plutus-contract-certification/README.md
- plutus-contract-certification/plutus-contract-certification.cabal
- plutus-contract-certification/src/Plutus/Contract/Test/Certification.hs
- plutus-contract-certification/src/Plutus/Contract/Test/Certification/Run.hs
- plutus-contract/src/Plutus/Contract/Test/ContractModel.hs
- plutus-contract/src/Plutus/Contract/Test/ContractModel/Internal.hs
- plutus-contract/src/Plutus/Contract/Test/Coverage.hs
- plutus-use-cases/plutus-use-cases.cabal
- plutus-use-cases/test/Spec/GameStateMachine.hs
- plutus-use-cases/test/Spec/Uniswap.hs
Framework for level 1 certification.
- Branch
- PR
> Certification framework

- plutus-contract/src/Wallet/Emulator/Wallet.hs
> When breaking off the calcFee recursion, pick the larger fee.

- plutus-pab-executables/demo/pab-nami/README.md
> Fixed pab-nami demo README for setting up Nami wallet's lib

- cabal.project
- deployment.nix
- nix/pkgs/haskell/materialized-darwin/.plan.nix/cardano-testnet.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/cardano-testnet.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/cardano-testnet.nix
- nix/pkgs/haskell/sha256map.nix
- plutus-example/test/Test/PlutusExample/Direct/CertifyingAndWithdrawingPlutus.hs
- plutus-example/test/Test/PlutusExample/Direct/ScriptContextEquality.hs
- plutus-example/test/Test/PlutusExample/Direct/ScriptContextEqualityMint.hs
- plutus-example/test/Test/PlutusExample/Direct/TxInLockingPlutus.hs
- plutus-example/test/Test/PlutusExample/Script/TxInLockingPlutus.hs
- plutus-example/test/Test/PlutusExample/SubmitApi/TxInLockingPlutus.hs
- shell.nix
https://github.com/input-output-hk/cardano-node/pull/3727 was backported to on top of `1.34` so that it coudl be used here.
- Branch
- PR
> Configurable configuration.yaml

- plutus-chain-index-core/src/Plutus/ChainIndex/Handlers.hs
> [chain-index]: return script and datum if present in getUtxoutFromRef

- plutus-streaming/src/Plutus/Streaming.hs
> You need to dup a broadcast channel in order to read.

- nix/pkgs/haskell/haskell.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-example.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-example.nix
- plutus-example/plutus-example.cabal
- plutus-example/test/plutus-example-test.hs
> Copy tests from plutus-example

- doc/plutus-doc.cabal
- doc/plutus/howtos/WriteScriptsTo.hs
- doc/plutus/tutorials/BasicPlutusTx.hs
- doc/plutus/tutorials/BasicPolicies.hs
- doc/plutus/tutorials/BasicValidators.hs
- doc/plutus/tutorials/Escrow.hs
- doc/plutus/tutorials/Escrow2.hs
- doc/plutus/tutorials/Escrow3.hs
- doc/plutus/tutorials/Escrow4.hs
- doc/plutus/tutorials/Escrow5.hs
- doc/plutus/tutorials/Escrow6.hs
- doc/plutus/tutorials/EscrowImpl.hs
- doc/plutus/tutorials/GameModel.hs
- doc/plutus/tutorials/HandlingBlockchainEvents.hs
- doc/plutus/tutorials/HelloWorldApp.hs
> Activated -Wmissing-import-lists for plutus-docs

- README.adoc
> SCP-3853: Write release, branching and dependency update policy of plutus-apps

- nix/pkgs/haskell/default.nix
- nix/pkgs/haskell/extra.nix
- release.nix
Ported from: https://github.com/input-output-hk/plutus/pull/4614/files
- Branch
- PR
> Update GHC version to 8.10.7 to get Mac builders unstuck.

- plutus-contract/plutus-contract.cabal
- plutus-contract/test/Spec.hs
- plutus-contract/test/Spec/TimeValidity.hs
- plutus-example/test/plutus-example-test.hs
> Add TimeValidity emulator test for different protocol versions

- plutus-pab/src/Plutus/PAB/App.hs
Cherry-picked commit from: https://github.com/etiennejf/plutus-apps/commit/124f4af586c337a71866f72b0a7a3dccbffa0fe8
- Branch
- PR
> plutus-pab: Set response timeout to 60 sec of HTTP requests

- plutus-contract/test/Spec/TimeValidity.hs
- plutus-example/test/Test/PlutusExample/Direct/CertifyingAndWithdrawingPlutus.hs
> Fix flakey CertifyingAndWithdrawingPlutus test with longer waits for Linux

- plutus-chain-index-core/src/Plutus/ChainIndex/Client.hs
> [chain-index]: export all servant client functions

- cabal.project
- nix/pkgs/haskell/haskell.nix
- plutus-streaming/README.md
- plutus-streaming/examples/Common.hs
- plutus-streaming/examples/Example1.hs
- plutus-streaming/examples/Example2.hs
- plutus-streaming/examples/Example3.hs
- plutus-streaming/examples/Orphans.hs
- plutus-streaming/plutus-streaming.cabal
- plutus-streaming/src/Plutus/Streaming.hs
Hi there,
this brings into main the plutus-streaming "library" I had written. I am using quotes because it's effectively one function :D
~It still has one bug where the user gets a STM exception if the chain-sync client cannot connect. I need to find a way to handle this.~ solved.
- Branch
- PR
> Add plutus-streaming package

- cabal.project
- nix/pkgs/haskell/sha256map.nix
- plutus-chain-index/app/Indexer.hs
- plutus-chain-index/plutus-chain-index.cabal
- plutus-chain-index/src/Cardano/Index/Datum.hs
- plutus-chain-index/src/Marconi/Index/Datum.hs
> Initial DatumHash -> Datum index implementation.

- .github/PULL_REQUEST_TEMPLATE.md
> Updated Github pull request template

- plutus-ledger-constraints/src/Ledger/Constraints/TxConstraints.hs
It's 2 lines of comment requested in #438.
> Comment MustSatisfyAnyOf.

- plutus-example/app/create-script-context.hs
- plutus-example/app/plutus-example.hs
- plutus-example/plutus-example.cabal
- plutus-example/src/PlutusExample/PlutusVersion1/AlwaysFails.hs
- plutus-example/src/PlutusExample/PlutusVersion1/AlwaysSucceeds.hs
- plutus-example/src/PlutusExample/PlutusVersion1/CustomDatumRedeemerGuess.hs
- plutus-example/src/PlutusExample/PlutusVersion1/DatumRedeemerGuess.hs
- plutus-example/src/PlutusExample/PlutusVersion1/Loop.hs
- plutus-example/src/PlutusExample/PlutusVersion1/MintingScript.hs
- plutus-example/src/PlutusExample/PlutusVersion1/RedeemerContextScripts.hs
- plutus-example/src/PlutusExample/PlutusVersion1/Sum.hs
- plutus-example/src/PlutusExample/PlutusVersion2/RequireRedeemer.hs
- plutus-example/src/PlutusExample/ScriptContextChecker.hs
- plutus-example/test/Test/PlutusExample/Gen.hs
- plutus-example/test/Test/PlutusExample/ScriptData.hs
Refactor plutus-example to make it easier to add future versions of plutus
Add an example plutus v2
> Create separate directories for v1 and v2 plutus scripts

- shell.nix
For the same reason as https://github.com/input-output-hk/plutus/pull/4684.
> Add pre-commit to shell.nix

- plutus-pab-executables/test/full/Plutus/PAB/CliSpec.hs
> Fix PAB CliSpec with conflicting ports between two test cases

- plutus-ledger/src/Ledger/Index.hs
> Don't take collateral if validation doesn't fail in phase 2

- scripts/cardano-node.sh
- shell.nix
Test run: https://buildkite.com/input-output-hk/plutus-script-evaluation/builds/21#
> PLT-333: Script for running a local node in buildkite

- scripts/create-dump.sh
This is the main script for the buildkite dump job. It runs a cardano local node and the script dump job.
> PLT-333: Script for running local node and dump job

- .buildkite/plutus-script-dump.yml
For pipeline: https://buildkite.com/input-output-hk/plutus-script-dump
> PLT-333: Buildkite pipeline for script dump job

- quickcheck-dynamic/src/Test/QuickCheck/DynamicLogic.hs
> Make quickcheck-dynamic compatible with ghc-9.2

- doc/plutus/tutorials/contract-models.rst
Some small improvements and proper haddock links everywhere.
- Branch
- PR
> Contract model tutorial cosmetics

- quickcheck-dynamic/test/Spec/DynamicLogic/RegistryModel.hs
> Fix quickcheck-dynamic registry model test #516.

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.adoc
- doc/README.md
- doc/adr/0001-record-architecture-decisions.rst
- doc/adr/index.rst
- doc/default.nix
- doc/index.rst
Added a new section in our readthedocs. 
Ultimately, this should be place where we document, propose and comment any architectural and design decisions in `plutus-apps`.
See: https://plutus-apps--512.org.readthedocs.build/en/512/
- Branch
- PR
> Bootstrap Architectural Design Records (ADR) in our documentation

- doc/plutus/tutorials/BasicAppConstraints.hs
- doc/plutus/tutorials/BasicApps.hs
- doc/plutus/tutorials/basic-apps-constraints.rst
- doc/plutus/tutorials/index.rst
> PLT-47 Add tutorial for using tx constraint API

- plutus-chain-index/plutus-chain-index.cabal
> Marconi remove unnecessary dependencies

- quickcheck-dynamic/src/Test/QuickCheck/DynamicLogic/Quantify.hs
> Fix module name in Quantify docs

- plutus-contract/test/Spec/Balancing.hs
- plutus-ledger/plutus-ledger.cabal
- plutus-ledger/src/Ledger/Test.hs
- plutus-ledger/src/Ledger/Tx.hs
- plutus-ledger/src/Ledger/Validation.hs
- plutus-ledger/test/Ledger/Tx/CardanoAPISpec.hs
This doesn't actually test that minting policy scripts are executed when calculating fees, but that would basically come down to writing tests for cardano-api, which I don't want to do unless we are sure something is wrong.
- Branch
- PR
> PLT-340: test minting policy issue

- doc/plutus/tutorials/contract-testing.rst
> Fix code location

- plutus-chain-index/src/Plutus/ChainIndex/Events.hs
Cherry-picked https://github.com/etiennejf/plutus-apps/commit/cd25afa44916483986978e8a8d787227d228f1b1 with some updates:
- replaced `break` with `span` for readability
- moved the logging out of the `processEvents`
- Branch
- PR
> [chain-index]: Handle rollback and resume events properly.

- deployment.nix
- doc/plutus-doc.cabal
- freer-extras/freer-extras.cabal
- playground-common/playground-common.cabal
- plutus-chain-index-core/plutus-chain-index-core.cabal
- plutus-chain-index/plutus-chain-index.cabal
- plutus-contract-certification/plutus-contract-certification.cabal
- plutus-contract/plutus-contract.cabal
- plutus-example/plutus-example.cabal
- plutus-ledger-constraints/plutus-ledger-constraints.cabal
- plutus-ledger/plutus-ledger.cabal
- plutus-pab-executables/plutus-pab-executables.cabal
- plutus-pab-executables/test/full/Plutus/PAB/CoreSpec.hs
- plutus-pab/plutus-pab.cabal
- plutus-playground-server/plutus-playground-server.cabal
- plutus-script-utils/plutus-script-utils.cabal
- plutus-streaming/plutus-streaming.cabal
- plutus-tx-constraints/plutus-tx-constraints.cabal
- plutus-use-cases/plutus-use-cases.cabal
- shell.nix
- web-ghc/web-ghc.cabal
* Updated the cardano-node bundled with plutus-apps to v1.35.0
* Updated version of all components in their respective cabal files to 1.0.0
- Branch
- PR
> Updated version of plutus-apps components to 1.0.0 and cardano-node to 1.35

- default.nix
- flake.nix
- plutus-chain-index/README_marconi.md
- Added the marconi executable as a Nix flake
- Added instructions on how to install the executable in the README
> PLT-361 Provide a flake to install the Marconi executable

- plutus-contract/src/Plutus/Contract/Test/ContractModel/Internal.hs
- plutus-ledger/src/Ledger/Validation.hs
> [plutus-ledger]: show CekError in CekEvaluationFailure error.

- plutus-ledger/README.md
The tutorial was moved in commit https://github.com/input-output-hk/plutus-apps/commit/5b9e7970aeb69d581645b24231b63a1754aa3327
This is the leftover code
- Branch
- PR
> Remove old tutorial section

- doc/plutus-doc.cabal
- freer-extras/freer-extras.cabal
- playground-common/playground-common.cabal
- plutus-chain-index-core/plutus-chain-index-core.cabal
- plutus-chain-index/plutus-chain-index.cabal
- plutus-contract-certification/plutus-contract-certification.cabal
- plutus-contract/plutus-contract.cabal
- plutus-example/plutus-example.cabal
- plutus-ledger-constraints/plutus-ledger-constraints.cabal
- plutus-ledger/plutus-ledger.cabal
- plutus-pab-executables/plutus-pab-executables.cabal
- plutus-pab/plutus-pab.cabal
- plutus-playground-server/plutus-playground-server.cabal
- plutus-script-utils/plutus-script-utils.cabal
- plutus-streaming/plutus-streaming.cabal
- plutus-tx-constraints/plutus-tx-constraints.cabal
- plutus-use-cases/plutus-use-cases.cabal
- web-ghc/web-ghc.cabal
The dependencies in the cabal files are separated in three categories:
- Local components
- Other IOG dependencies
- Non-IOG dependencies
Feel free to propose different categories
- Branch
- PR
> Reorganized the dependencies (build-depends) in the cabal files

- playground-common/src/PSGenerator/Common.hs
- plutus-chain-index-core/src/Plutus/ChainIndex/Api.hs
- plutus-chain-index-core/src/Plutus/ChainIndex/Client.hs
- plutus-chain-index-core/src/Plutus/ChainIndex/Effects.hs
- plutus-chain-index-core/src/Plutus/ChainIndex/Emulator/Handlers.hs
- plutus-chain-index-core/src/Plutus/ChainIndex/Handlers.hs
- plutus-chain-index-core/src/Plutus/ChainIndex/Server.hs
- plutus-contract/src/Plutus/Contract/Effects.hs
- plutus-contract/src/Plutus/Contract/Request.hs
- plutus-contract/src/Plutus/Contract/Trace/RequestHandler.hs
- plutus-pab-executables/demo/pab-nami/client/generated/Plutus/ChainIndex/Api.purs
- plutus-pab-executables/demo/pab-nami/client/generated/Plutus/Contract/Effects.purs
- plutus-pab/src/Plutus/PAB/Core.hs
- plutus-pab/src/Plutus/PAB/Simulator.hs
- plutus-playground-client/generated/Plutus/ChainIndex/Api.purs
- plutus-playground-client/generated/Plutus/Contract/Effects.purs
> PLT-308: Add UnspentTxOutsAt query

- doc/plutus-doc.cabal
- freer-extras/freer-extras.cabal
- playground-common/playground-common.cabal
- plutus-chain-index-core/plutus-chain-index-core.cabal
- plutus-chain-index/plutus-chain-index.cabal
- plutus-contract-certification/plutus-contract-certification.cabal
- plutus-contract/plutus-contract.cabal
- plutus-example/plutus-example.cabal
- plutus-ledger-constraints/plutus-ledger-constraints.cabal
- plutus-ledger/README.md
- plutus-ledger/plutus-ledger.cabal
- plutus-pab-executables/plutus-pab-executables.cabal
- plutus-pab/plutus-pab.cabal
- plutus-playground-server/plutus-playground-server.cabal
- plutus-script-utils/plutus-script-utils.cabal
- plutus-streaming/plutus-streaming.cabal
- plutus-tx-constraints/plutus-tx-constraints.cabal
- plutus-use-cases/plutus-use-cases.cabal
- web-ghc/web-ghc.cabal
Merge #574  and #575 from main into next-node
- Branch
- PR
> Merge #574 and #575 from main into next-node

- default.nix
- Added `create-script-context` to our nix flake
> Issue #580 - Build create-script-context with Nix

- cabal.project
- nix/pkgs/haskell/sha256map.nix
* Update cardano-node dependency to 1.35.1
* Updated cardano-wallet, plutus and cardano-ledger to match the node
version.
- Branch
- PR
> Update cardano-node dependency to 1.35.1

- plutus-chain-index/app/Marconi/Index/Utxo.hs
- plutus-chain-index/plutus-chain-index.cabal
> Fix utxo sync delay.

- plutus-streaming/examples/Example2.hs
The datums function was wrong. This replaces the whole example with
working functions.
- Branch
- PR
> Fix plutus-streaming-example-2

- doc/requirements.txt
> Require markdown 3.3.7

- README.adoc
> Added precision on the meaning of the first-major version of plutus-apps

- plutus-ledger-constraints/src/Ledger/Constraints/OffChain.hs
- plutus-ledger-constraints/src/Ledger/Constraints/OnChain.hs
- plutus-ledger/src/Ledger/Generators.hs
- plutus-ledger/src/Ledger/Index.hs
- plutus-ledger/test/Spec.hs
> Add zero ada to mint and fee fields to match cardano-ledger behaviour

- .github/workflows/plutus-playground-e2e-tests.yml
- Changed GHA to reflect the changes introduced by https://github.com/input-output-hk/plutus-apps/pull/559
> Fix Plutus Plauground Nightly E2E Test

- plutus-script-utils/src/Plutus/Script/Utils/V1/Typed/Scripts.hs
> Fix a typo of PubKeyTxOut

- doc/plutus/tutorials/EscrowImpl.hs
- plutus-chain-index-core/src/Plutus/ChainIndex/Emulator/Handlers.hs
- plutus-chain-index-core/src/Plutus/ChainIndex/Handlers.hs
- plutus-chain-index-core/src/Plutus/ChainIndex/Types.hs
- plutus-contract/src/Plutus/Contract/StateMachine.hs
- plutus-ledger-constraints/src/Ledger/Constraints/OffChain.hs
- plutus-ledger-constraints/test/Spec.hs
- plutus-ledger/src/Ledger/Tx.hs
- plutus-ledger/src/Ledger/Tx/CardanoAPI.hs
- plutus-playground-server/usecases/Game.hs
- plutus-use-cases/src/Plutus/Contracts/Escrow.hs
- plutus-use-cases/src/Plutus/Contracts/Game.hs
- plutus-use-cases/src/Plutus/Contracts/Tutorial/Escrow.hs
- plutus-use-cases/src/Plutus/Contracts/Tutorial/EscrowStrict.hs
- plutus-use-cases/src/Plutus/Contracts/Uniswap/OffChain.hs
- plutus-use-cases/test/Spec/Escrow/Endpoints.hs
> [PLT-81] plutus-chain-index: support inline scripts when querying TxOut of a TxOutRef

- plutus-chain-index-core/notes/ConnectingToTheTestnet.md
- plutus-pab-executables/tx-inject/start-all-servers.sh
- plutus-pab/test-node/activate-contract.sh
- plutus-pab/test-node/cleanup.sh
- plutus-pab/test-node/start-alonzo-purple-node.sh
- plutus-pab/test-node/start-node-01.sh
- plutus-pab/test-node/start-node-02.sh
- plutus-pab/test-node/start-testnet-node.sh
> Replace `#!/bin/bash` with `#!/usr/bin/env bash`

- plutus-hysterical-screams/README.md
Fix a typo `In`.
- Branch
- PR
> Fix typo In

- doc/adr/0004-marconi-initiative.rst
- doc/adr/0005-pab-indexing-solution-integration.rst
- doc/adr/index.rst
ADR regarding problem with PAB's integration with indexing solutions.
This was triggered by the issue #473. A temporary fix was submitted by #544, but the ideal solution should be the one presented in this ADR.
The ADR is found here: https://plutus-apps--550.org.readthedocs.build/en/550/adr/0004-pab-indexing-solution-integration.html
- Branch
- PR
> PLT-359 ADR regarding problem with PAB's integration with indexing solutions.

- cabal.project
- nix/pkgs/haskell/sha256map.nix
- plutus-chain-index/app/Marconi.hs
- plutus-chain-index/app/Marconi/Index/Datum.hs
- plutus-chain-index/app/Marconi/Index/Utxo.hs
- plutus-chain-index/plutus-chain-index.cabal
- plutus-hysterical-screams/README.md
Some references to old repository were still present.
This PR addresses that.
> Remove old references to hysterical-screams

- plutus-contract/src/Wallet/Emulator/Chain.hs
cardano-ledger validation rules are prioritized over our custom validation rules when validating transaction in the emulator.
Simple change, but creating a PR for this in order to make sure everything compiles and all test cases pass.
Should fix the test case of https://github.com/input-output-hk/plutus-apps/pull/624
- Branch
- PR
> cardano-ledger validation rules are prioritized over custom validaton rules

- bitte/static-site.nix
Fix formatting of a nix file `static-site.nix` to make it looks more systematic.
- Branch
- PR
> Fix static-site.nix formatting

- cabal.project
- nix/pkgs/haskell/sha256map.nix
Also updates plutus and cardano-ledger.
- Branch
- PR
> Update cardano-node to 1.35.3-rc1 with deps

- plutus-contract/plutus-contract.cabal
- plutus-contract/test/Spec.hs
- plutus-contract/test/Spec/MustSpendAtLeast.hs
> Add mustSpendAtLeast Constraint tests

- doc/adr/0007-support-reference-inputs-in-constraint-library.rst
- doc/adr/index.rst
> PLT-682 ADR for the constraint interface change following support for reference inputs

- bitte/static-site.nix
- cabal.project
- doc/adr/0006-common-contract-api.rst
- doc/adr/0007-support-reference-inputs-in-constraint-library.rst
- doc/adr/index.rst
- nix/pkgs/haskell/sha256map.nix
- plutus-chain-index/app/Marconi.hs
- plutus-chain-index/app/Marconi/Index/Datum.hs
- plutus-chain-index/app/Marconi/Index/Utxo.hs
- plutus-chain-index/plutus-chain-index.cabal
- plutus-contract/plutus-contract.cabal
- plutus-contract/src/Wallet/Emulator/Chain.hs
- plutus-contract/src/Wallet/Emulator/MultiAgent.hs
- plutus-contract/src/Wallet/Emulator/Wallet.hs
- plutus-contract/test/Spec.hs
- plutus-contract/test/Spec/TxConstraints/MustSpendAtLeast.hs
- plutus-contract/test/Spec/TxConstraints/RequiredSigner.hs
- plutus-contract/test/Spec/TxConstraints/TimeValidity.hs
- plutus-hysterical-screams/README.md
- plutus-ledger-constraints/src/Ledger/Constraints/OffChain.hs
- plutus-ledger-constraints/src/Ledger/Constraints/OnChain/V1.hs
- plutus-ledger-constraints/src/Ledger/Constraints/TxConstraints.hs
- plutus-ledger/src/Ledger/Index.hs
- plutus-use-cases/test/Spec/renderGuess.txt
> Merge main into next-node (2022-08-12)

- plutus-contract/test/Spec/Contract/TxConstraints.hs
- plutus-ledger-constraints/src/Ledger/Constraints.hs
- plutus-ledger-constraints/src/Ledger/Constraints/OffChain.hs
- plutus-ledger-constraints/src/Ledger/Constraints/OnChain/V1.hs
- plutus-ledger-constraints/src/Ledger/Constraints/OnChain/V2.hs
- plutus-ledger-constraints/src/Ledger/Constraints/TxConstraints.hs
- plutus-tx-constraints/src/Ledger/Tx/Constraints.hs
- plutus-tx-constraints/src/Ledger/Tx/Constraints/OffChain.hs
- plutus-use-cases/test/Spec/future.pir
> PLT-670: MustReferenceOutput

- doc/adr/0008-support-inline-datums-in-constraint-library.rst
- doc/adr/index.rst
ADR for the constraint interface change following supporting inline datums
- Branch
- PR
> PLT-682 ADR for the constraint interface change following supporting inline datums

- doc/adr/0009-support-reference-scripts-in-constraint-library.rst
- doc/adr/index.rst
> Plt 684 adr interface changes to the transaction constraint library for working with reference scripts

- cabal.project
- nix/pkgs/haskell/sha256map.nix
Very straightforward - just updates the tag which points to the exact same commit.
> SCP-4354 Bump `plutus-apps/next-node` branch version

- doc/conf.py
- doc/index.rst
> new doc title and revised intro

- freer-extras/src/Control/Monad/Freer/Extras.hs
Add one more space (3 -> 4), and sort modules
- Branch
- PR
> Fix indentation of modules

- doc/index.rst
> very minor edit to Tools Intro

- plutus-contract/plutus-contract.cabal
- plutus-contract/test/Spec.hs
- plutus-contract/test/Spec/TxConstraints/MustMint.hs
> Add tests for MustMint tx constraint

- plutus-contract/src/Plutus/Contract/StateMachine.hs
- plutus-contract/src/Plutus/Contract/StateMachine/OnChain.hs
- plutus-contract/src/Plutus/Contract/Test/ContractModel/DoubleSatisfaction.hs
- plutus-ledger-constraints/src/Ledger/Constraints.hs
- plutus-ledger-constraints/src/Ledger/Constraints/OffChain.hs
- plutus-ledger-constraints/src/Ledger/Constraints/OnChain/V1.hs
- plutus-ledger-constraints/src/Ledger/Constraints/OnChain/V2.hs
- plutus-ledger-constraints/src/Ledger/Constraints/TxConstraints.hs
- plutus-ledger/src/Ledger/Scripts.hs
- plutus-ledger/src/Ledger/Tx/CardanoAPI.hs
- plutus-pab/src/Plutus/PAB/Arbitrary.hs
- plutus-tx-constraints/src/Ledger/Tx/Constraints.hs
- plutus-tx-constraints/src/Ledger/Tx/Constraints/OffChain.hs
- plutus-use-cases/src/Plutus/Contracts/Tutorial/Escrow.hs
- plutus-use-cases/src/Plutus/Contracts/Tutorial/EscrowStrict.hs
- plutus-use-cases/src/Plutus/Contracts/Uniswap/OnChain.hs
- plutus-use-cases/test/Spec/future.pir
- plutus-use-cases/test/Spec/renderGuess.txt
This is part of my work on PLT-448. Actually writing tests is blocked on the chain index reporting plutus language versions, but I think this part is reviewable as one whole so I'd like to merge it to not let the changes go stale.
- Branch
- PR
> PLT-448: inline scripts in constraint libraries

- nix/pkgs/haskell/haskell.nix
- rewindable-index/rewindable-index.cabal
- rewindable-index/src/RewindableIndex/Index.hs
- rewindable-index/src/RewindableIndex/Index/Split.hs
- rewindable-index/src/RewindableIndex/Index/Sqlite.hs
- rewindable-index/src/RewindableIndex/Index/VSplit.hs
- rewindable-index/src/RewindableIndex/Index/VSqlite.hs
- rewindable-index/test/RewindableIndex/Spec/Index.hs
- rewindable-index/test/RewindableIndex/Spec/Split.hs
- rewindable-index/test/RewindableIndex/Spec/Sqlite.hs
- rewindable-index/test/RewindableIndex/Spec/VSplit.hs
- rewindable-index/test/RewindableIndex/Spec/VSqlite.hs
- rewindable-index/test/Spec.hs
* Added missing import lists
* Removed unused packages
* Explicitly throw running error in non-exhaustif pattern match
- Branch
- PR
> Activated -Werror in nix configuration for rewindable-index package.

- rewindable-index/rewindable-index.cabal
Fix a typo in `iohk.io` domain
- Branch
- PR
> Fix iohk email domain

- plutus-contract/plutus-contract.cabal
- plutus-contract/test/Spec.hs
- plutus-contract/test/Spec/TxConstraints/MustProduceAtLeast.hs
> Add MustProduceAtLeast tx constraint tests

- doc/adr/0007-support-reference-inputs-in-constraint-library.rst
- doc/adr/0009-support-reference-scripts-in-constraint-library.rst
- doc/adr/0010-marconi-indexer-rollbacks.rst
- doc/adr/0011-support-return-and-total-collateral-when-building-transactions.rst
- doc/adr/index.rst
Added an ADR to detail the strategy of supporting the return and total collateral fields in a transaction body.
Also, took the time to write some very minor updates to the other ADRs.
- Branch
- PR
> PLT-685 ADR for supporting return and total collateral when building transactions

- plutus-ledger-constraints/src/Ledger/Constraints/OffChain.hs
- plutus-ledger-constraints/src/Ledger/Constraints/OnChain/V1.hs
- plutus-ledger-constraints/src/Ledger/Constraints/OnChain/V2.hs
- plutus-ledger-constraints/src/Ledger/Constraints/TxConstraints.hs
- plutus-ledger-constraints/test/Spec.hs
> PLT-454: mustUseOutputAsCollateral

- plutus-contract/plutus-contract.cabal
- plutus-contract/test/Spec.hs
- plutus-contract/test/Spec/TxConstraints/MustProduceAtLeast.hs
- plutus-contract/test/Spec/TxConstraints/MustSpendPubKeyOutput.hs
> Add MustSpendPubKeyOutputs tests

- default.nix
- marconi/README.md
We must update nix now that marconi has its own directory
- Branch
- PR
> Move marconi executable to the right directory

- cabal.project
- plutus-contract/plutus-contract.cabal
- plutus-contract/test/Spec.hs
- plutus-contract/test/Spec/TxConstraints/MustIncludeDatum.hs
> Add tests for mustIncludeDatum tx constraint

- cabal.project
- plutus-contract/plutus-contract.cabal
- plutus-contract/test/Spec.hs
- plutus-contract/test/Spec/TxConstraints/MustPayToPubKeyAddress.hs
> Add tests for MustPayToPubKeyAddress tx constraint

- plutus-contract/plutus-contract.cabal
- plutus-contract/test/Spec.hs
- plutus-contract/test/Spec/TxConstraints/MustSpendScriptOutput.hs
- plutus-ledger-constraints/src/Ledger/Constraints/OffChain.hs
…hingDatumAndValue tx constraints
- Branch
- PR
> Add tests for mustSpendScriptOutput and mustSpendScriptOutputWithMatchingDatumAndValue tx constraints

- plutus-contract-certification/src/Plutus/Contract/Test/Certification/Run.hs
... and a function `certificationTasks` to tell you which tasks will run.
> Add a certification event for number of QuickCheck tests about to be run

- plutus-contract/plutus-contract.cabal
- plutus-contract/test/Spec.hs
- plutus-contract/test/Spec/TxConstraints/MustMint.hs
- plutus-contract/test/Spec/TxConstraints/MustPayToOtherScript.hs
- plutus-contract/test/Spec/TxConstraints/MustPayToPubKeyAddress.hs
- plutus-contract/test/Spec/TxConstraints/MustSpendScriptOutput.hs
- plutus-ledger/src/Ledger/Test.hs
... and 2 more for mustPayToPubKeyAddress
- Branch
- PR
> Add tests for mustPayToOtherScript tx constraint

- plutus-contract/src/Wallet/Effects.hs
- plutus-contract/src/Wallet/Emulator/Wallet.hs
- plutus-pab/src/Cardano/Wallet/LocalClient.hs
- plutus-pab/src/Cardano/Wallet/Mock/API.hs
- plutus-pab/src/Cardano/Wallet/Mock/Client.hs
- plutus-pab/src/Cardano/Wallet/RemoteClient.hs
In short, we won't be using the wallet to query blockchain information. This is the responsability of the indexing component. See [ADR-5](https://plutus-apps.readthedocs.io/en/latest/adr/0005-pab-indexing-solution-integration.html) for more details.
- Branch
- PR
> PLT-646 Removed the TotalFunds effect of WalletEffect.

- plutus-contract/test/Spec/TxConstraints/MustSpendScriptOutput.hs
- plutus-ledger-constraints/src/Ledger/Constraints/OnChain/V2.hs
> Make MustSpendScriptOutput check redeemer on-chain

- marconi/app/Main.hs
Add optional cli param to specify list of utxo script addresses to index in the Address->Utxo indexer. and filter for those indices only.  See [PLT-862](https://input-output.atlassian.net/browse/PLT-862) for additional detail
- Branch
- PR
> marconi CLI list index PLT-599

- release.nix
> Don't require the darwin jobs to succeed for now until the mac-minis are fixed in C

- doc/adr/0012-commit-to-data-types-in-cardano-api.rst
- doc/adr/index.rst
See https://plutus-apps--734.org.readthedocs.build/en/734/adr/0012-commit-to-datatypes-in-cardano-api.html
- Branch
- PR
> PLT-360 ADR documenting our decision to commit the cardano-api package

- plutus-contract-certification/src/Plutus/Contract/Test/Certification/Run.hs
Previously `Tasty.Result`s got turned into strings.
> Add proper ToJSON instance for unit test results

- plutus-use-cases/test/Spec/Crowdfunding.hs
Will be reactivated once https://github.com/input-output-hk/plutus-apps/issues/754 is resolved.
- Branch
- PR
> Deactivate Crowdfunding QuickCheck ContractModel test case.

- plutus-contract/plutus-contract.cabal
- plutus-contract/test/Spec.hs
- plutus-contract/test/Spec/TxConstraints/MustSatisfyAnyOf.hs
- plutus-ledger/src/Ledger/Test.hs
> Add MustSatisfyAnyOf plutus-contract tests

- plutus-contract/plutus-contract.cabal
- plutus-contract/test/Spec.hs
- plutus-contract/test/Spec/TxConstraints/MustIncludeDatum.hs
- plutus-contract/test/Spec/TxConstraints/MustReferenceOutput.hs
- plutus-contract/test/Spec/TxConstraints/MustSpendPubKeyOutput.hs
- plutus-contract/test/Spec/TxConstraints/MustSpendScriptOutput.hs
> Add mustReferenceOutput constraint tests

- plutus-use-cases/src/Plutus/Contracts.hs
- plutus-use-cases/src/Plutus/Contracts/Crowdfunding.hs
- plutus-use-cases/src/Plutus/Contracts/Escrow.hs
- plutus-use-cases/src/Plutus/Contracts/Governance.hs
- plutus-use-cases/src/Plutus/Contracts/MultiSigStateMachine.hs
- plutus-use-cases/src/Plutus/Contracts/SealedBidAuction.hs
- plutus-use-cases/src/Plutus/Contracts/SimpleEscrow.hs
- plutus-use-cases/test/Spec.hs
- plutus-use-cases/test/Spec/Auction.hs
- plutus-use-cases/test/Spec/Crowdfunding.hs
- plutus-use-cases/test/Spec/Escrow.hs
- plutus-use-cases/test/Spec/Prism.hs
- plutus-use-cases/test/Spec/SealedBidAuction.hs
- plutus-use-cases/test/Spec/crowdfunding.pir
- plutus-use-cases/test/Spec/crowdfundingEmulatorTestOutput.txt
- plutus-use-cases/test/Spec/renderCrowdfunding.txt
Should fix #759 
* Fixed the SealedBidAuction failing quickcheck test case
* Documented the issue concerning validity intervals and outlined the issue with cardano-ledger.
* Added a global limit of 100 for number of generated test cases for quickcheck. This can be override on individual property tests using 'withMaxSuccess'.
* Added a test case for Crowdfunding to verify that we can't make a contribution if the deadline is elapsed (unrelated to the fix, but I encountered the lack of test for this test case when looking at the validity intervals)
- Branch
- PR
> PLT-1034 Fixed SealedBidAuction failing quickcheck test case.

- marconi/test/Integration.hs
- plutus-use-cases/test/Spec/Prism.hs
This PR is a copy of #774. Trying to workaround issue in hydra build.
- Branch
- PR
> PLT-1035 Fix an off by one error in prism test

- doc/adr/0005-pab-indexing-solution-integration.rst
- plutus-chain-index-core/src/Plutus/ChainIndex/Tx.hs
- plutus-chain-index-core/src/Plutus/ChainIndex/TxIdState.hs
- plutus-contract/src/Wallet/Emulator/Chain.hs
- plutus-contract/src/Wallet/Emulator/MultiAgent.hs
- plutus-contract/src/Wallet/Emulator/Wallet.hs
- plutus-contract/src/Wallet/Graph.hs
- plutus-contract/src/Wallet/Rollup.hs
- plutus-contract/test/Spec/Balancing.hs
- plutus-contract/test/Spec/golden/traceOutput - pubKeyTransactions.txt
- plutus-contract/test/Spec/golden/traceOutput - pubKeyTransactions2.txt
- plutus-ledger-constraints/test/Spec.hs
- plutus-ledger/src/Ledger/AddressMap.hs
- plutus-ledger/src/Ledger/Blockchain.hs
- plutus-ledger/src/Ledger/Generators.hs
- plutus-ledger/src/Ledger/Tx.hs
- plutus-ledger/src/Ledger/Tx/CardanoAPI.hs
- plutus-ledger/src/Ledger/Tx/CardanoAPI/Internal.hs
- plutus-ledger/src/Ledger/Tx/CardanoAPITemp.hs
- plutus-ledger/src/Ledger/Tx/Internal.hs
- plutus-pab/src/Plutus/PAB/Simulator.hs
- plutus-use-cases/src/Plutus/Contracts/PubKey.hs
- plutus-use-cases/test/Spec/crowdfundingEmulatorTestOutput.txt
- plutus-use-cases/test/Spec/renderCrowdfunding.txt
- plutus-use-cases/test/Spec/renderGuess.txt
- plutus-use-cases/test/Spec/renderVesting.txt
Accidentally merged the previous PR (#740) into next-node...
- Branch
- PR
> PLT-774: Collateral output

- deployment.nix
- shell.nix
> Updated the cardano-node and cardano-wallet versions that are provided in the nix-shell

- plutus-contract/src/Wallet/Emulator/Wallet.hs
- plutus-contract/test/Spec/TxConstraints/MustSpendPubKeyOutput.hs
- plutus-contract/test/Spec/golden/traceOutput - pubKeyTransactions.txt
- plutus-contract/test/Spec/golden/traceOutput - pubKeyTransactions2.txt
- plutus-ledger/src/Ledger/Tx/CardanoAPI.hs
- plutus-use-cases/test/Spec/crowdfundingEmulatorTestOutput.txt
- plutus-use-cases/test/Spec/renderCrowdfunding.txt
- plutus-use-cases/test/Spec/renderGuess.txt
- plutus-use-cases/test/Spec/renderVesting.txt
> GTH-692: Don't add collateral when not needed

- plutus-pab-executables/demo/pab-nami/pab/plutus-pab.yaml
- plutus-pab-executables/plutus-pab.yaml.sample
- plutus-pab/src/Cardano/Node/Client.hs
- plutus-pab/src/Cardano/Node/Types.hs
- plutus-pab/src/Plutus/PAB/App.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance/BlockchainEnv.hs
- plutus-pab/src/Plutus/PAB/Run/Cli.hs
- plutus-pab/test-node/testnet/pab-config.yml
* https://github.com/etiennejf/plutus-apps/commit/a43d1e097a7f5bffa92293c425d74b4542786fb7
* https://github.com/etiennejf/plutus-apps/commit/ebe40e55cdedb84e4cccca3431753c3ff9505c79
CC @etiennejf 
- Branch
- PR
> Add new 'NodeMode' constructor for disabling chain sync events

- plutus-pab/src/Plutus/PAB/Run/Cli.hs
* https://github.com/etiennejf/plutus-apps/commit/5e94d447af8dce9e6f558b352a93912eea470754
cc @etiennejf 
- Branch
- PR
> Restore running PAB contracts only when not in InMemoryBackend mode

- plutus-pab/src/Plutus/PAB/Core.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance/STM.hs
- plutus-pab/src/Plutus/PAB/Simulator.hs
- plutus-pab/src/Plutus/PAB/Webserver/Handler.hs
* https://github.com/etiennejf/plutus-apps/commit/bc138b70270b9b8036f59fba631f9857ab941fda
* https://github.com/etiennejf/plutus-apps/commit/7362598d454f1fa2ad1c516f73e9791622599f2a
* https://github.com/etiennejf/plutus-apps/commit/bfe6f0ba18ae64f25b46893a5296139b934dcfea
cc @etiennejf 
- Branch
- PR
> Delete instances from InstancesState and connection maps when status is no more active

- playground-common/playground-common.cabal
- playground-common/src/PSGenerator/Common.hs
- plutus-contract/src/Plutus/Contract.hs
- plutus-contract/src/Plutus/Contract/Effects.hs
- plutus-contract/src/Plutus/Contract/Request.hs
- plutus-contract/src/Plutus/Contract/StateMachine.hs
- plutus-contract/src/Plutus/Contract/Trace.hs
- plutus-contract/src/Plutus/Contract/Trace/RequestHandler.hs
- plutus-contract/src/Plutus/Contract/Wallet.hs
- plutus-contract/src/Plutus/Trace/Emulator/ContractInstance.hs
- plutus-contract/src/Wallet/API.hs
- plutus-contract/test/Spec/Balancing.hs
- plutus-ledger-constraints/src/Ledger/Constraints.hs
- plutus-ledger-constraints/src/Ledger/Constraints/OffChain.hs
- plutus-ledger-constraints/test/Spec.hs
- plutus-ledger/src/Ledger/Params.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance.hs
- plutus-use-cases/src/Plutus/Contracts/Prism/Unlock.hs
- plutus-use-cases/test/Spec/crowdfundingEmulatorTestOutput.txt
> PLT-1011: Add mkTxWithParams

- plutus-pab-executables/plutus-pab.yaml.sample
- plutus-pab/plutus-pab.cabal
- plutus-pab/src/Plutus/PAB/Types.hs
- plutus-pab/src/Plutus/PAB/Webserver/Server.hs
> PLT-1197: Support HTTPS for PAB webserver

- README.adoc
Copied from plutus.
- Branch
- PR
> Updated the Nix cache information in the README

- marconi/app/Main.hs
- marconi/src/Marconi/CLI.hs
Filter the target addresses that are going to be indexed with the CLI format: --with-address <addr1>
- Branch
- PR
> marconi change TargetAddress CLI format PLT-1014

- cabal.project
- flake.lock
- flake.nix
- freer-extras/test/Control/Monad/Freer/Extras/BeamSpec.hs
- nix/lib/purescript.nix
- nix/modules/web-ghc.nix
- nix/pkgs/default.nix
- nix/pkgs/haskell/sha256map.nix
- nix/pkgs/sphinx-markdown-tables/default.nix
- nix/pkgs/update-client-deps/default.nix
- nix/pkgs/web-ghc/default.nix
- nix/tests/vm.nix
- playground-common/src/Language/Haskell/Interpreter.hs
- plutus-chain-index-core/test/Plutus/ChainIndex/HandlersSpec.hs
- plutus-chain-index/src/Plutus/ChainIndex/Lib.hs
- plutus-pab/src/Plutus/PAB/App.hs
- plutus-pab/src/Plutus/PAB/Arbitrary.hs
- shell.nix
hackage and haskell are ~6 months old, so we update them.
Also to please the folks at Quviq who need newer packages. 
This will trigger a GHC rebuild, so it's going to take a while for hydra to finish.
This will also trigger a rebuild of lots of cabal packages, so maybe haskell code will break.
> Bump haskell.nix and hackage.nix

- plutus-contract/src/Plutus/Contract/Test.hs
- plutus-contract/test/Spec/Contract/Tx/Constraints/MustMint.hs
> PLT-909: Implement walletFundsAssetClassChange

- marconi/app/Main.hs
- marconi/marconi.cabal
- marconi/src/Marconi/CLI.hs
Reduce the number of CLI parameters required for marconi. We now ask for the directory structure to create the database related files. If the directory does not exist, we will create it.
see [PLT-1224](https://input-output.atlassian.net/browse/PLT-1224) for detail
- Branch
- PR
> marconi-mamba-reduce-cli-params PLT-1224

- marconi-mamba/README.md
> Fix broken link in marconi-mamba README.md

- plutus-chain-index-core/src/Plutus/ChainIndex/Emulator/Handlers.hs
- plutus-chain-index-core/src/Plutus/ChainIndex/Types.hs
- plutus-chain-index-core/test/Plutus/ChainIndex/Emulator/HandlersSpec.hs
- plutus-chain-index-core/test/Plutus/ChainIndex/HandlersSpec.hs
- plutus-contract/test/Spec/Contract.hs
- plutus-contract/test/Spec/golden/traceOutput - pubKeyTransactions.txt
- plutus-contract/test/Spec/golden/traceOutput - pubKeyTransactions2.txt
- plutus-contract/test/Spec/golden/traceOutput - wait1.txt
> PLT-1040: fix currentChainIndexSlot

- doc/adr/0015-time-conversion.rst
- doc/adr/index.rst
- shell.nix
* Added the ADR in the RTD
* Fixed the nix-shell cardano-node version which was out of date
- Branch
- PR
> PLT-1222 ADR about changing the slot to time conversions in the emulator and PAB

- doc/adr/0005-pab-indexing-solution-integration.rst
- doc/plutus/tutorials/BasicApps.hs
- doc/plutus/tutorials/EscrowImpl.hs
- doc/plutus/tutorials/basic-apps.rst
- plutus-contract/src/Plutus/Contract/StateMachine.hs
- plutus-contract/src/Plutus/Contract/StateMachine/OnChain.hs
- plutus-contract/src/Wallet/Emulator/MultiAgent.hs
- plutus-contract/src/Wallet/Emulator/Wallet.hs
- plutus-contract/test/Spec/Contract.hs
- plutus-contract/test/Spec/Contract/Tx/Constraints/MustIncludeDatum.hs
- plutus-contract/test/Spec/Contract/Tx/Constraints/MustMint.hs
- plutus-contract/test/Spec/Contract/Tx/Constraints/MustPayToOtherScript.hs
- plutus-contract/test/Spec/Contract/Tx/Constraints/MustPayToPubKeyAddress.hs
- plutus-contract/test/Spec/Contract/Tx/Constraints/MustReferenceOutput.hs
- plutus-contract/test/Spec/Contract/Tx/Constraints/MustSatisfyAnyOf.hs
- plutus-contract/test/Spec/Emulator.hs
- plutus-ledger-constraints/src/Ledger/Constraints.hs
- plutus-ledger-constraints/src/Ledger/Constraints/OffChain.hs
- plutus-ledger-constraints/src/Ledger/Constraints/OnChain/V1.hs
- plutus-ledger-constraints/src/Ledger/Constraints/OnChain/V2.hs
- plutus-ledger-constraints/src/Ledger/Constraints/TxConstraints.hs
- plutus-ledger-constraints/test/Spec.hs
- plutus-ledger/src/Ledger/Tx/CardanoAPI/Internal.hs
- plutus-pab/src/Plutus/PAB/Arbitrary.hs
- plutus-tx-constraints/src/Ledger/Tx/Constraints.hs
- plutus-tx-constraints/src/Ledger/Tx/Constraints/OffChain.hs
- plutus-use-cases/src/Plutus/Contracts/Uniswap/OnChain.hs
- plutus-use-cases/test/Spec/renderGuess.txt
It's probably best to review this commit by commit, since the changes are not related.
- Branch
- PR
> PLT-910: babbage technical debt

- plutus-contract/plutus-contract.cabal
- plutus-contract/src/Plutus/Contract/Test.hs
- plutus-contract/test/Spec/Contract/Tx/Constraints/MustUseOutputAsCollateral.hs
- plutus-contract/test/Spec/Contract/Tx/Constraints/Spec.hs
> Add mustUseOutputAsCollateral tests and renamed test function 'tx'

- doc/plutus/tutorials/BasicAppConstraints.hs
> Fix a doctest that dodge PR 842

- .github/workflows/test.yml
- Dockerfile
- README.adoc
- flake.nix
... and thanks for all the fish!
> So long hydra

- plutus-contract/changelog.d/20221128_060044_konstantinos.lambrou_minting_policy_antipattern.md
- plutus-contract/src/Wallet/Emulator/LogMessages.hs
- plutus-contract/src/Wallet/Emulator/Types.hs
- plutus-contract/src/Wallet/Emulator/Wallet.hs
- plutus-contract/test/Spec/Contract/Tx/Constraints/MustReferenceOutput.hs
- plutus-contract/test/Spec/Emulator.hs
- plutus-ledger-constraints/src/Ledger/Constraints/OffChain.hs
- plutus-ledger/changelog.d/20221128_103738_nicolas.biri_minAdaTxOut.md
- plutus-ledger/changelog.d/20221201_143837_sjoerd.visscher_PLT_321_makeAutoBalancedTransactionWithWalletOutputs.md
- plutus-ledger/src/Ledger/Fee.hs
- plutus-ledger/src/Ledger/Index.hs
- plutus-ledger/src/Ledger/Tx.hs
- plutus-ledger/src/Ledger/Tx/CardanoAPI.hs
> PLT-321: Implement makeAutoBalancedTransactionWithUtxoProvider

- plutus-contract/test/Spec/Contract/Tx/Constraints/MustIncludeDatum.hs
- plutus-contract/test/Spec/Contract/Tx/Constraints/MustReferenceOutput.hs
- plutus-ledger-constraints/changelog.d/20221205_152425_sjoerd.visscher_plt_321_no_offchain_logic_for_datum_constraints.md
- plutus-ledger-constraints/src/Ledger/Constraints/OffChain.hs
- plutus-ledger-constraints/test/Spec.hs
- plutus-tx-constraints/src/Ledger/Tx/Constraints/OffChain.hs
> PLT-321: Remove off-chain checks for datum constraints

- marconi/marconi.cabal
- marconi/src/Marconi/Index/ScriptTx.hs
- marconi/src/Marconi/Indexers.hs
- marconi/test/Integration.hs
- rewindable-index/src/RewindableIndex/Storable.hs
- rewindable-index/test/RewindableIndex/Spec/Sqlite.hs
> Use the new indexer api in the existing indexers.

- plutus-contract/src/Wallet/Emulator/Wallet.hs
- plutus-contract/test/Spec/Balancing.hs
- plutus-contract/test/Spec/Contract/Tx/Constraints/MustMint.hs
- plutus-contract/test/Spec/Contract/Tx/Constraints/MustPayToOtherScript.hs
- plutus-ledger-constraints/src/Ledger/Constraints/OffChain.hs
- plutus-ledger/src/Ledger/Fee.hs
- plutus-ledger/src/Ledger/Test.hs
- plutus-ledger/src/Ledger/Tx/CardanoAPI.hs
- plutus-tx-constraints/changelog.d/20221212_095505_nicolas.biri_must_mint.md
- plutus-tx-constraints/plutus-tx-constraints.cabal
- plutus-tx-constraints/src/Ledger/Tx/Constraints/OffChain.hs
> [PLT-672] implement MustMintValue for tx-constraints

- plutus-contract/changelog.d/20221213_131533_nicolas.biri_PLT_501.md
- plutus-contract/plutus-contract.cabal
- plutus-contract/src/Plutus/Contract/Test.hs
- plutus-contract/test/Spec/Contract/Error.hs
- plutus-contract/test/Spec/Contract/Tx/Constraints/MustIncludeDatum.hs
- plutus-contract/test/Spec/Contract/Tx/Constraints/MustMint.hs
- plutus-contract/test/Spec/Contract/Tx/Constraints/MustPayToOtherScript.hs
- plutus-contract/test/Spec/Contract/Tx/Constraints/MustPayToPubKeyAddress.hs
- plutus-contract/test/Spec/Contract/Tx/Constraints/MustProduceAtLeast.hs
- plutus-contract/test/Spec/Contract/Tx/Constraints/MustReferenceOutput.hs
- plutus-contract/test/Spec/Contract/Tx/Constraints/MustSatisfyAnyOf.hs
- plutus-contract/test/Spec/Contract/Tx/Constraints/MustSpendAtLeast.hs
- plutus-contract/test/Spec/Contract/Tx/Constraints/MustSpendPubKeyOutput.hs
- plutus-contract/test/Spec/Contract/Tx/Constraints/MustSpendScriptOutput.hs
- plutus-contract/test/Spec/Contract/Tx/Constraints/RequiredSigner.hs
- plutus-contract/test/Spec/Contract/Tx/Constraints/TimeValidity.hs
- plutus-contract/test/Spec/Emulator.hs
- plutus-ledger-constraints/src/Ledger/Constraints/OffChain.hs
- plutus-script-utils/changelog.d/20221213_131043_nicolas.biri_PLT_501.rst
- plutus-script-utils/src/Plutus/Script/Utils/Typed.hs
- plutus-use-cases/test/Spec/MultiSig.hs
- plutus-use-cases/test/Spec/crowdfundingEmulatorTestOutput.txt
- plutus-use-cases/test/Spec/renderCrowdfunding.txt
- plutus-use-cases/test/Spec/renderGuess.txt
- plutus-use-cases/test/Spec/renderVesting.txt
> PLT-501 Trace unsafeFromBuiltinData in typed validation

- cardano-streaming/examples/Example1.hs
- cardano-streaming/examples/Example2.hs
- cardano-streaming/examples/Example3.hs
- cardano-streaming/src/Cardano/Streaming.hs
- marconi-mamba/src/Marconi/Bootstrap.hs
- marconi/app/Main.hs
- marconi/marconi.cabal
- marconi/src/Marconi/CLI.hs
- marconi/src/Marconi/Index/ScriptTx.hs
- marconi/src/Marconi/Indexers.hs
- marconi/test/Integration.hs
- rewindable-index/src/RewindableIndex/Storable.hs
> Enable resumes for the ScriptTx indexer.

- plutus-contract/changelog.d/20221220_085332_nicolas.biri_PLT_857.md
- plutus-contract/plutus-contract.cabal
- plutus-contract/src/Plutus/Contract/Test/ContractModel/DoubleSatisfaction.hs
- plutus-ledger/src/Ledger/Tx/CardanoAPI.hs
- plutus-ledger/src/Ledger/Tx/Internal.hs
- plutus-use-cases/test/Spec/Auction.hs
> PLT-857 Use Cardano Tx in Double satisfaction

- marconi/test/Integration.hs
I'm checking if it solves the CI issues
- Branch
- PR
> use current directory in marconi integration test

- plutus-contract/test/Spec/Contract/Tx/Constraints/MustMint.hs
- plutus-tx-constraints/src/Ledger/Tx/Constraints/OffChain.hs
Not related to any ticket, but I bumped into it while looking at the test code base and can't resist updating it.
- Branch
- PR
> Add MustMint tests for CardanoTx taking advantage of the CardanoTx balancing

- plutus-contract/changelog.d/20230116_082351_nicolas.biri_TxRequest.md
- plutus-contract/src/Plutus/Contract.hs
- plutus-contract/src/Plutus/Contract/Error.hs
- plutus-contract/src/Plutus/Contract/Request.hs
- plutus-contract/test/Spec/Contract/Tx/Constraints/MustMint.hs
- plutus-contract/test/Spec/Contract/Tx/Constraints/MustProduceAtLeast.hs
- plutus-contract/test/Spec/Contract/Tx/Constraints/MustReferenceOutput.hs
- plutus-contract/test/Spec/Contract/Tx/Constraints/MustSpendAtLeast.hs
- plutus-contract/test/Spec/Contract/Tx/Constraints/RequiredSigner.hs
- plutus-ledger/src/Ledger/Tx/CardanoAPI/Internal.hs
> PLT-1350 Add submitTx* functions for cardano Tx

- cardano-node-emulator/src/Cardano/Node/Emulator/Generators.hs
- plutus-ledger/plutus-ledger.cabal
- plutus-ledger/src/Ledger/Tx/CardanoAPI/Internal.hs
- plutus-ledger/test/Spec.hs
> PLT-354: CardanoBuildTx To/FromJSON instances

- __std__/cells/plutus-apps/library/haskell-language-server-project.nix
- __std__/cells/plutus-apps/library/make-plutus-apps-project.nix
- __std__/flake.lock
- __std__/flake.nix
- flake.lock
- flake.nix
- nix/pkgs/haskell/extra.nix
We can't seem to get 1.9 but 1.8 seems to work
> Bump Haskell Language Server to 1.8.0.0

- __std__/cells/plutus-apps/packages/cabal-fmt.nix
- nix/pkgs/haskell/extra.nix
See https://github.com/phadej/cabal-fmt/pull/68
> Bump cabal-fmt

- cardano-node-emulator/changelog.d/20230201_135624_sjoerd.visscher_PLT_1356_MaxCollateralInputs.md
- cardano-node-emulator/src/Cardano/Node/Emulator/Fee.hs
- plutus-chain-index-core/plutus-chain-index-core.cabal
- plutus-contract/src/Plutus/Contract/Test.hs
- plutus-contract/test/Spec/Contract/Tx/Constraints/MustUseOutputAsCollateral.hs
- plutus-contract/test/Spec/golden/traceOutput - pubKeyTransactions.txt
- plutus-contract/test/Spec/golden/traceOutput - pubKeyTransactions2.txt
- plutus-ledger/src/Ledger/Index/Internal.hs
I don't have a test to check that the changed coin selection algorithm improves the situation, because the amount of collateral is hard to control. But I can see from the changed traceoutput files that the code is doing what I want it to do.
I do have a test for throwing an error when overflowing the maximum number of collateral inputs.
- Branch
- PR
> PLT-1356: Balancing takes max collateral inputs into account

- plutus-e2e-tests/test/Spec/BabbageFeatures.hs
- plutus-e2e-tests/test/Spec/Builtins/SECP256k1.hs
> Fix failing darwin 'permission denied' in CI

- __std__/cells/plutus-apps/library/make-plutus-apps-project.nix
- __std__/cells/plutus-apps/packages/default.nix
- __std__/cells/plutus-apps/packages/marconi-chain-index.nix
- __std__/cells/plutus-apps/packages/marconi.nix
Forgot to modify the `std` files in the last [PR](https://github.com/input-output-hk/plutus-apps/pull/933)
- Branch
- PR
> Forgot to modify the `std` file in a previous PR

- cabal.project
- nix/pkgs/haskell/sha256map.nix
- plutus-contract/src/Plutus/Contract/Test/ContractModel/Internal.hs
> Update contractmodel dependency to latest version on master

- plutus-contract/test/Spec/Contract.hs
- plutus-contract/test/Spec/Contract/Tx/Constraints/MustSatisfyAnyOf.hs
Only one test was still relevant.
- Branch
- PR
> PLT-1451: Move constraint tests out of Spec.Contract

- marconi-chain-index/app/Main.hs
- marconi-chain-index/changelog.d/20230217_163000_kayvank_lint.md
- marconi-chain-index/marconi-chain-index.cabal
- marconi-chain-index/src/Marconi/ChainIndex/CLI.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/EpochStakepoolSize.hs
- marconi-chain-index/test-lib/Helpers.hs
- marconi-chain-index/test/Spec.hs
- marconi-chain-index/test/Spec/Golden/Cli/marconi-chain-index___disable_address_data.help
- marconi-chain-index/test/Spec/Golden/Cli/marconi-chain-index___help.help
- marconi-chain-index/test/Spec/Marconi/ChainIndex/CLI.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/EpochStakepoolSize.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/ScriptTx.hs
- marconi-mamba/changelog.d/20230217_162500_kayvank_lint.md
- marconi-mamba/src/Marconi/Mamba/CLI.hs
- marconi-mamba/test/Spec/Golden/Cli/marconi-mamba___help.help
- marconi-mamba/test/Spec/Golden/Cli/marconi-mamba___socket.help
- marconi-mamba/test/Spec/Golden/Cli/marconi.help
- marconi-mamba/test/Spec/Golden/Cli/marconi___addresses_to_index.help
- marconi-mamba/test/Spec/Golden/Cli/marconi___help.help
- marconi-mamba/test/Spec/Golden/Cli/marconi___http_port.help
- marconi-mamba/test/Spec/Golden/Cli/marconi___utxo_db.help
fix: 
- marconi-chain-index lint errors/warnings
- golden tests for marconi-mamba
- golden tests for marconi-chain-index
- Branch
- PR
> Plt 1513 marconi fix lint errors warnings

- README.adoc
- doc/index.rst
- doc/plutus/howtos/getting-started.rst
> Add a deprecation warning in front of the plutus-starter references

- plutus-ledger/test/Ledger/Tx/CardanoAPISpec.hs
- plutus-tx-constraints/plutus-tx-constraints.cabal
- plutus-tx-constraints/src/Ledger/Tx/Constraints/OffChain.hs
- plutus-tx-constraints/test/Spec.hs
> Add lacking plutus-tx-constraints tests

- cardano-node-emulator/src/Cardano/Node/Emulator/Params.hs
- plutus-pab-executables/examples/uniswap/Main.hs
- plutus-pab-executables/plutus-pab-executables.cabal
- plutus-use-cases/src/Plutus/Contracts/Uniswap/Trace.hs
- plutus-use-cases/test/Spec/Uniswap.hs
> PLT-620: Fix and enable prop_Uniswap

- __std__/README.md
- flake.nix
> Update flake.nix comments

- marconi-chain-index/README.md
- marconi-chain-index/README_MARCONI_DRAFT.md
- marconi-sidechain/README.md
* Rename the old `marconi-chain-index` README.md to README_MARCONI_DRAFT as it represents the README for the Marconi project as a whole. Will probably be used elsewhere.
* Update the `marconi-sidechain` README with latest changes and added some instructions on how to build it.
* Create a README for `marconi-chain-index` with a similar format to `marconi-sidechain` as they share many similar things. This will be worked on more in the future.
Note: The diff in the `marconi-chain-index/README.md` can be glanced over very quickly, as it's basically the same as the `marconi-sidechain/README.md` (minus the JSON-RPC server)
- Branch
- PR
> PLT-1459: Updated README of marconi-chain-index and marconi-sidechain

- plutus-e2e-tests/plutus-e2e-tests.cabal
- plutus-e2e-tests/test/Helpers/Testnet.hs
- plutus-e2e-tests/test/Helpers/Tx.hs
- plutus-e2e-tests/test/Helpers/Utils.hs
- plutus-e2e-tests/test/Spec/AlonzoFeatures.hs
- plutus-e2e-tests/test/Spec/BabbageFeatures.hs
- plutus-e2e-tests/test/Spec/Builtins/SECP256k1.hs
By SIGTERM and then SIGKILL if not stopped. Hopefully avoid hanging processes in CI.
- Branch
- PR
> Handle process termination of node instances at end of each e2e test

- cabal.project
Just clarifying a comment left in cabal.project, so we know what we have to do in the future.
> Clarify comment on cabal.project

- cabal.project
- doc/plutus-doc.cabal
- flake.lock
- nix/pkgs/haskell/sha256map.nix
- plutus-contract-certification/plutus-contract-certification.cabal
- plutus-contract/plutus-contract.cabal
- plutus-ledger/plutus-ledger.cabal
- plutus-use-cases/plutus-use-cases.cabal
> Depend on iog version of quickcheck-contractmodel

- .github/workflows/haddock.yml
> Build and deploy Haddock to Github pages

- .github/workflows/haddock.yml
- .github/workflows/pre-commit-check.yml
- .github/workflows/script-evaluation-dump.yml
> Downgrading the nix version to 2.13.3 in workflows because of a bug in Nix 2.14.1

- marconi-chain-index/src/Marconi/ChainIndex/CLI.hs
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/EpochState.hs
- marconi-sidechain/README.md
- marconi-sidechain/marconi-sidechain.cabal
- marconi-sidechain/src/Marconi/Sidechain/Api/HttpServer.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Query/Indexers/EpochState.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Routes.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Types.hs
- marconi-sidechain/src/Marconi/Sidechain/Bootstrap.hs
- marconi-sidechain/test/Spec/Marconi/Sidechain/Api/Routes/Golden/epoch-nonce-response.json
- marconi-sidechain/test/Spec/Marconi/Sidechain/Routes.hs
> PLT-170-2 Add JSON-RPC querying for nonce by epoch in marconi-sidechain

- doc/adr/0018-Indexers-query-synchronisation-primitive.rst
- doc/adr/0018-hearing-hysterical-streams.rst
- doc/adr/index.rst
- marconi-core/marconi-core.cabal
- marconi-core/src/Marconi/Core/TracedStorable.hs
- marconi-core/test/Marconi/Core/Model.hs
- marconi-core/test/Marconi/Core/Spec/TracedSqlite.hs
- marconi-core/test/Marconi/Core/Trace.hs
- marconi-core/test/Spec.hs
> Notifications - Model, implementation and tests.

- cardano-node-emulator/cardano-node-emulator.cabal
- cardano-node-emulator/changelog.d/20230331_165428_sjoerd.visscher_plt_5389_mtl_contractmodel.md
- cardano-node-emulator/src/Cardano/Node/Emulator/MTL.hs
- cardano-node-emulator/src/Cardano/Node/Emulator/MTL/Test.hs
- cardano-node-emulator/test/Cardano/Node/Emulator/MTLSpec.hs
- plutus-contract/src/Plutus/Contract/Test/ContractModel/Internal.hs
- plutus-ledger/src/Ledger/Tx/CardanoAPI/Internal.hs
- plutus-tx-constraints/plutus-tx-constraints.cabal
- plutus-tx-constraints/test/Game.hs
- plutus-tx-constraints/test/Spec.hs
- plutus-tx-constraints/test/Spec/Balancing.hs
> PLT-5389: Contract model tests for MTL-based node emulator code

- marconi-chain-index/bench/BenchQueries.hs
- marconi-chain-index/changelog.d/20230403_070417_nicolas.biri_current_indexed_slot.md
- marconi-chain-index/src/Marconi/ChainIndex/Indexers/Utxo.hs
- marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/Utxo/UtxoIndex.hs
- marconi-sidechain/README.md
- marconi-sidechain/changelog.d/20230403_070847_nicolas.biri_current_indexed_slot.md
- marconi-sidechain/src/Marconi/Sidechain/Api/HttpServer.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Query/Indexers/Utxo.hs
- marconi-sidechain/src/Marconi/Sidechain/Api/Types.hs
- marconi-sidechain/test/Spec/Marconi/Sidechain/Api/Query/Indexers/Utxo.hs
> marconi utxo query: Add query to get the current indexed slot

- plutus-use-cases/src/Plutus/Contracts/Governance.hs
- plutus-use-cases/test/Spec/Governance.hs
I have defined a contract model to test the governance contract. 
Changes in law do not have a monetary impact so it was not possible to check this without adding an additional off-chain endpoint called `CheckLaw`. This endpoint simply queries the state of the contract and has no on-chain impact. Work will soon be done by Quviq so that this no longer needs to be done using off-chain code.
I have enabled code coverage for this contract so the transaction size has increased. I therefore had to add additional transaction limits to the existing tests. 
I have added comments to the contract model and all tests have passed on my system. 
- Branch
- PR
> Definition of contract model for the Governance contract

- cabal.project
- cardano-node-emulator/cardano-node-emulator.cabal
- cardano-node-emulator/src/Cardano/Node/Emulator/MTL/Test.hs
- flake.lock
- nix/pkgs/haskell/sha256map.nix
- plutus-contract/plutus-contract.cabal
- plutus-contract/src/Plutus/Contract/Test/ContractModel/Interface.hs
- plutus-contract/src/Plutus/Contract/Test/ContractModel/Internal.hs
- plutus-ledger/plutus-ledger.cabal
- plutus-tx-constraints/plutus-tx-constraints.cabal
- plutus-use-cases/plutus-use-cases.cabal
- plutus-use-cases/src/Plutus/Contracts/Governance.hs
- plutus-use-cases/test/Spec/Escrow.hs
- plutus-use-cases/test/Spec/Governance.hs
This fixes the need for custom endpoints as used e.g. in the Governance example.
- Branch
- PR
> ContractModel: add the ability to perform observations of the blockchain in `DL` properties

- cardano-node-emulator/cardano-node-emulator.cabal
- cardano-node-emulator/changelog.d/20230418_172119_sjoerd.visscher_PLT_5512_emulator_logging.md
- cardano-node-emulator/src/Cardano/Node/Emulator/MTL.hs
- cardano-node-emulator/src/Cardano/Node/Emulator/MTL/LogMessages.hs
- cardano-node-emulator/src/Cardano/Node/Emulator/MTL/Test.hs
- cardano-node-emulator/test/Cardano/Node/Emulator/MTLSpec.hs
- cardano-node-emulator/test/Cardano/Node/Emulator/golden/logs - payToAddress.txt
- doc/plutus/tutorials/basic-apps-trace.txt
- plutus-contract/src/Wallet/Emulator/Folds.hs
- plutus-contract/src/Wallet/Emulator/LogMessages.hs
- plutus-contract/src/Wallet/Emulator/Wallet.hs
- plutus-contract/test/Spec/golden/traceOutput - pubKeyTransactions.txt
- plutus-contract/test/Spec/golden/traceOutput - pubKeyTransactions2.txt
- plutus-ledger/src/Ledger/Tx.hs
- plutus-tx-constraints/plutus-tx-constraints.cabal
- plutus-tx-constraints/test/Game.hs
- plutus-tx-constraints/test/Spec/Balancing.hs
- plutus-use-cases/test/Spec/crowdfundingEmulatorTestOutput.txt
> PLT-5512: emulator logging

- cabal.project
- cardano-node-emulator/cardano-node-emulator.cabal
- flake.lock
- nix/pkgs/haskell/sha256map.nix
- plutus-contract/plutus-contract.cabal
- plutus-contract/src/Plutus/Contract/Test/ContractModel/CrashTolerance.hs
- plutus-contract/src/Plutus/Contract/Test/ContractModel/Interface.hs
- plutus-contract/src/Plutus/Contract/Test/ContractModel/Internal.hs
- plutus-ledger/plutus-ledger.cabal
- plutus-tx-constraints/plutus-tx-constraints.cabal
- plutus-use-cases/plutus-use-cases.cabal
- plutus-use-cases/test/Spec/Escrow.hs
- plutus-use-cases/test/Spec/Governance.hs
> ContractModel: update quickcheck-contractmodel dependency to implement symbolic TxOuts

- cardano-node-emulator/src/Cardano/Node/Emulator/Fee.hs
- plutus-ledger/src/Ledger/Index.hs
- plutus-tx-constraints/src/Ledger/Tx/Constraints/OffChain.hs
> Remove adjustTxOut duplicaton

- cardano-node-emulator/cardano-node-emulator.cabal
- cardano-node-emulator/src/Cardano/Node/Emulator.hs
- cardano-node-emulator/src/Cardano/Node/Emulator/Chain.hs
- cardano-node-emulator/src/Cardano/Node/Emulator/Fee.hs
- cardano-node-emulator/src/Cardano/Node/Emulator/Generators.hs
- cardano-node-emulator/src/Cardano/Node/Emulator/MTL.hs
- cardano-node-emulator/src/Cardano/Node/Emulator/MTL/LogMessages.hs
- cardano-node-emulator/src/Cardano/Node/Emulator/MTL/Test.hs
- cardano-node-emulator/src/Cardano/Node/Emulator/Params.hs
- cardano-node-emulator/src/Cardano/Node/Emulator/TimeSlot.hs
- cardano-node-emulator/src/Cardano/Node/Emulator/Validation.hs
- cardano-node-emulator/test/Cardano/Node/Emulator/GeneratorsSpec.hs
- cardano-node-emulator/test/Cardano/Node/Emulator/MTLSpec.hs
- cardano-node-emulator/test/Spec.hs
and activated -Wmissing-imports-list flag.
- Branch
- PR
> Made all imports explicit in cardano-node-emulator

- cardano-node-emulator/src/Cardano/Node/Emulator/MTL.hs
- plutus-tx-constraints/test/Plutus/Example/GameSpec.hs
Added CardanoAddress as parameter to Cardano.Node.Emulator.MTL.submitTxConfirmed  for signing the transaction
- Branch
- PR
> Added CardanoAddress as parameter to Cardano.Node.Emulator.MTL.submitTxConfirmed

- plutus-contract/src/Plutus/Contract/Test.hs
> PLT-5926: Also output emulator logs on success.

- STYLEGUIDE.adoc
The PR is at the moment a WIP, we need to discuss its content before merging it.
- Branch
- PR
> Add initial coding style

- cardano-node-emulator/cardano-node-emulator.cabal
- cardano-node-emulator/src/Cardano/Node/Emulator/API.hs
- cardano-node-emulator/src/Cardano/Node/Emulator/Internal/Node/Fee.hs
- cardano-node-emulator/test/Plutus/Example/Game.hs
- cardano-node-emulator/test/Plutus/Example/GameSpec.hs
- cardano-node-emulator/test/Spec.hs
- plutus-contract/src/Plutus/Contract/Effects.hs
- plutus-contract/src/Plutus/Contract/Request.hs
- plutus-contract/src/Plutus/Contract/Trace/RequestHandler.hs
- plutus-contract/src/Wallet/API.hs
- plutus-ledger/src/Ledger/Index.hs
- plutus-tx-constraints/plutus-tx-constraints.cabal
- plutus-tx-constraints/src/Ledger/Tx/Constraints/OffChain.hs
- plutus-tx-constraints/test/Spec.hs
- plutus-tx-constraints/test/Spec/Balancing.hs
The second commit is the implementation of the actual ticket. The other two commits are refactorings.
- Branch
- PR
> PLT-5567: game contract with cardano-api

- cardano-node-socket-emulator/cardano-node-socket-emulator.cabal
- cardano-node-socket-emulator/src/Cardano/Node/Socket/Emulator/Chain.hs
- cardano-node-socket-emulator/src/Cardano/Node/Socket/Emulator/Server.hs
- plutus-chain-index-core/plutus-chain-index-core.cabal
- plutus-chain-index-core/src/Cardano/Protocol/Socket/Type.hs
- plutus-pab-executables/tx-inject/Main.hs
- plutus-pab/src/Cardano/Protocol/Socket/Mock/Client.hs
- plutus-pab/src/Cardano/Wallet/Mock/Server.hs
- plutus-pab/src/Plutus/PAB/App.hs
This is a work in progress, but I want to merge this since the change otherwise wont survive the move to a new repo.
- Branch
- PR
> Start of node compatible socket interface

- nix/pkgs/haskell/sha256map.nix
Removed `git-sha` maps of previous dependencies that are no longer required.
- Branch
- PR
> minor clean up of nix dependencies

- __std__/cells/plutus-apps/devshells/plutus-apps-shell.nix
> Remove use-cases from nix shell

- plutus-example/src/PlutusExample/ScriptContextChecker.hs
This fixes https://github.com/input-output-hk/plutus-apps/issues/1078 by using different `TextEnvelopeType` when deserializing text envelope. 
Repro in `cardan-api` : https://github.com/input-output-hk/cardano-api/pull/29
cc: @newhoggy @Jimbo4350 
- Branch
- PR
> #1078 Use correct envelope type when decoding it

- README.adoc
> Maintenance mode
