input-output-hk/plutus-apps

plutus-chain-index/app/Main.hs

This work is part of #69.
The printed slot number is only half helpful. The primary purpose of this query is to get the first response of the node for potential errors before opening the DB and starting the chain index.
When the socket does not exist:
```
Query the tip of the local node: 
plutus-chain-index: Network.Socket.connect: <socket: 78>: does not exist (No such file or directory)
```
When the network magics do not match:
```
Query the tip of the local node: 
plutus-chain-index: HandshakeError (Refused NodeToClientV_9 "version data mismatch: NodeToClientVersionData {networkMagic = NetworkMagic {unNetworkMagic = 1097911063}} /= NodeToClientVersionData {networkMagic = NetworkMagic {unNetworkMagic = 1097911062}}")
```
When it works:
```
Query the tip of the local node:
SlotNo 41320486 …
```

Chain Index app: query the tip of the node for first response before start

---

plutus-contract/src/Plutus/Contract/Test/ContractModel.hs
plutus-use-cases/test/Spec/Auction.hs

Some contracts have offchain code that runs in the background (e.g. the `Auction` example contract). This PR introduces a simple change to `ContractModel` that makes it possible to model these reactive state changes faithfully.
- Branch
- PR

Reactive state updates in contract models

---

plutus-chain-index/src/Plutus/ChainIndex/Config.hs
plutus-contract/src/Wallet/Emulator/Chain.hs
plutus-contract/src/Wallet/Emulator/Types.hs
plutus-contract/src/Wallet/Emulator/Wallet.hs
plutus-contract/test/Spec/Emulator.hs
plutus-ledger/src/Ledger/Generators.hs
plutus-ledger/src/Ledger/Index.hs
plutus-pab/plutus-pab.yaml.sample
plutus-pab/src/Cardano/Chain.hs
plutus-pab/src/Cardano/Node/Mock.hs
plutus-pab/src/Cardano/Node/Server.hs
plutus-pab/src/Cardano/Protocol/Socket/Mock/Server.hs
plutus-pab/src/Plutus/PAB/Simulator.hs
plutus-pab/sync-client/Main.hs
plutus-pab/test-node/testnet/chain-index-config.json
plutus-pab/test-node/testnet/pab-config.yml
plutus-pab/tx-inject/TxInject/RandomTx.hs
plutus-pab/tx-inject/config.yaml

This PR attempts to fix a misconfigured slot config issue we found while working with PAB. It started with a wrong Shelley launch time in `plutus-pab/plutus-pab.yaml.sample`, which leads to weird off-chain validation errors when we use `mustValidateIn` constraints.
The quick fix was to update the config file with the "correct" Shelley launch date, but this PR provides the general fix that removes the bug for good.
The flow starts with `mustValidateIn`, which adds the validity range to the `UnbalancedTx`:
https://github.com/input-output-hk/plutus-apps/blob/942bd8c6de6a2d5981d91c704b0258bddd9d9d7c/plutus-ledger/src/Ledger/Constraints/OffChain.hs#L505-L506
Which is eventually balanced here:
https://github.com/input-output-hk/plutus-apps/blob/942bd8c6de6a2d5981d91c704b0258bddd9d9d7c/plutus-con …

PAB: More consistent slot configs

---

plutus-contract/src/Plutus/Contract/StateMachine.hs
plutus-contract/src/Plutus/Trace/Effects/Waiting.hs
plutus-contract/src/Plutus/Trace/Emulator.hs
plutus-contract/src/Plutus/Trace/Playground.hs

Triggered by the review of #77. 
The only remaining instance that we should get rid of is in `awaitTime` in `Plutus.PAB.Core.ContractInstance.STM`.
- Branch
- PR

Don't use default slotConfig where this was easily fixable.

---

plutus-use-cases/test/Spec/Auction.hs
plutus-use-cases/test/Spec/Crowdfunding.hs

The failing test case can be run using:
```
cabal test plutus-use-cases --test-options="-p \"crowdfunding.QuickCheck ContractModel\" --quickcheck-replay=714845"
```
This corrects a bug resulting from the PR #76 
- Branch
- PR

SCP-3064: Fixed failing test case in the Crowdfunding plutus use case

---

plutus-pab/test-node/testnet/pab-config.yml

The current pab-config.yml uses an outdated wallet config that will throw an error, this can be especially confusing to users trying to do the integration test example. This PR will update the config to be compliant with the current wallet configuration.

Update pab-config.yml to work with latest wallet config

---

freer-extras/src/Control/Monad/Freer/Extras/Modify.hs
plutus-contract/src/Plutus/Contract/Types.hs

This may seem silly, but I needed this for `M = 6` and `N = 3`.
The `mapEffs` function seems generally useful, so I suggested to add it to `freer-simple`: https://github.com/lexi-lambda/freer-simple/issues/37
- Branch
- PR

Add raiseMUnderN to freer-extras

---

plutus-chain-index-core/src/Plutus/ChainIndex/Handlers.hs

Fix #124, when `utxo-at-adress` returns the incorrect set of utxos including the spent ones.
---
- Branch
- PR

[plutus-chain-index]: fix utxo-at-adress beam query (#124).

---

nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-pab.nix
nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-pab.nix
nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-pab.nix
plutus-pab/plutus-pab.cabal
plutus-pab/src/Plutus/PAB/Arbitrary.hs
plutus-pab/test/light/Plutus/PAB/ArbitrarySpec.hs
plutus-pab/test/light/Spec.hs

By using sized we can have an arbitrary instance that actually
terminates and is configurable via standard QuickCheck
methods (e.g. generate, resize). This will allow testing with Datums and
will prevent users unintentionally stalling their tests when generating
Datums, BuiltinData, and Data. Fixes #172.

Write arbitrary instance for data that uses sized

---

nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-chain-index-core.nix
nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-chain-index.nix
nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-chain-index-core.nix
nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-chain-index.nix
nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-chain-index-core.nix
nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-chain-index.nix
plutus-chain-index-core/plutus-chain-index-core.cabal
plutus-chain-index-core/src/Cardano/Protocol/Socket/Client.hs
plutus-chain-index-core/src/Plutus/ChainIndex.hs
plutus-chain-index-core/src/Plutus/ChainIndex/Effects.hs
plutus-chain-index-core/src/Plutus/ChainIndex/Emulator/Handlers.hs
plutus-chain-index-core/src/Plutus/ChainIndex/Handlers.hs
plutus-chain-index-core/src/Plutus/ChainIndex/Server.hs
plutus-chain-index-core/src/Plutus/ChainIndex/Types.hs
plutus-chain-index-core/test/Plutus/ChainIndex/Emulator/HandlersSpec.hs
plutus-chain-index-core/test/Plutus/ChainIndex/HandlersSpec.hs
plutus-chain-index/plutus-chain-index.cabal
plutus-chain-index/src/Plutus/ChainIndex/App.hs
plutus-chain-index/src/Plutus/ChainIndex/Config.hs
plutus-chain-index/src/Plutus/ChainIndex/Lib.hs
plutus-contract/src/Plutus/Trace/Emulator/System.hs
plutus-pab/local-cluster/Main.hs
plutus-pab/src/Plutus/PAB/Core/ContractInstance/BlockchainEnv.hs
plutus-pab/sync-client/Main.hs

Refactoring so the chain index can be used more easily as a library, with the following goals.
- Clear entry point `Plutus.ChainIndex.Lib` which collects and documents what's needed to run a chain index.
- Separated out functions in a more modular way so:
- a user can select the parts they do and don't want to use
- there are clear extension points for custom code.
- Allow for custom effects when executing the chain index effects.
The main focus in this PR is on `ChainSyncHandler`s, since customising what to sync and store is the biggest request (see `filterTxs`), and to make it easy to run the syncing once you have built such a handler.
This is just a first step, we expect to be building this out over the coming months.
- Branch
- PR

SCP-3127: Chain index as a library

---

ci.nix
nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-contract.nix
nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-contract.nix
nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-contract.nix
plutus-contract/plutus-contract.cabal
plutus-contract/src/Plutus/Contract/Oracle.hs
plutus-contract/src/Wallet/Emulator/Wallet.hs
plutus-contract/test/Spec.hs
plutus-contract/test/Spec/Plutus/Contract/Oracle.hs
plutus-ledger/src/Ledger/CardanoWallet.hs
plutus-ledger/src/Ledger/Crypto.hs
plutus-ledger/src/Ledger/Generators.hs
plutus-ledger/src/Ledger/Orphans.hs
plutus-ledger/src/Ledger/Tx.hs
plutus-ledger/test/Spec.hs
plutus-pab/src/Cardano/Wallet/Mock/Handlers.hs
plutus-use-cases/test/Spec/Future.hs
plutus-use-cases/test/Spec/Stablecoin.hs
release.nix

This addresses #168; Instead of having the passphrase for signing
hardcoded to "Ledger.Crypto PassPhrase", allow the passphrase to be
provided. This way we aren't prevented from using private keys
created with tools like cardano-address and cardano-cli

Add passphrase to ledger signing api

---

nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-contract.nix
nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-contract.nix
nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-contract.nix
plutus-contract/plutus-contract.cabal
plutus-contract/src/Plutus/Contract.hs
plutus-contract/src/Plutus/Contract/Logging.hs
plutus-contract/src/Plutus/Contract/Request.hs
plutus-contract/src/Plutus/Contract/StateMachine.hs
plutus-contract/src/Plutus/Trace/Emulator/Extract.hs
plutus-contract/src/Wallet/Emulator/Folds.hs
plutus-ledger-constraints/src/Ledger/Constraints/OffChain.hs
plutus-ledger/src/Ledger/Typed/Scripts/Validators.hs
plutus-ledger/src/Ledger/Typed/TypeUtils.hs
plutus-use-cases/scripts/Main.hs

Add some logging to extract the arguments and results of all calls to `mkTx`. 
```haskell
{-| Arguments and result of a call to 'mkTx'
-}
data MkTxLog =
MkTxLog
{ mkTxLogLookups       :: ScriptLookups Any
, mkTxLogTxConstraints :: TxConstraints PlutusTx.BuiltinData PlutusTx.BuiltinData
, mkTxLogResult        :: Either Constraints.MkTxError UnbalancedTx
}
deriving stock (Show, Generic)
deriving anyclass (ToJSON, FromJSON)
```
The JSON objects are values of the `MkTxLog` type. To get the results, run `mkdir tmp && cabal run plutus-use-cases-scripts -- ./tmp mktx`.
[Example](https://gist.github.com/j-mueller/352798e4004cef94298037e2869b0f2b)
- Branch
- PR

SCP-3147: MkTx JSON logs

---

plutus-pab-executables/src/Plutus/PAB/Run/PSGenerator.hs
plutus-pab/src/Plutus/PAB/Run/Cli.hs
plutus-pab/src/Plutus/PAB/Webserver/API.hs
plutus-pab/src/Plutus/PAB/Webserver/Handler.hs
plutus-pab/src/Plutus/PAB/Webserver/Server.hs

Don't proxy the wallet backend through our webserver anymore.
Fixes SCP-3096
TODO:
The main change here is `curl` calls like this:
```
> curl -s -d '' http://localhost:9080/wallet/create
```
go direct to the wallet server instead:
```
> curl -s -d '' http://localhost:9081/create
```
- Branch
- PR

SCP-3096 - Remove wallet proxy

---

nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-pab-executables.nix
nix/pkgs/haskell/materialized-darwin/default.nix
nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-pab-executables.nix
nix/pkgs/haskell/materialized-linux/default.nix
nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-pab-executables.nix
nix/pkgs/haskell/materialized-windows/default.nix
playground-common/src/PSGenerator/Common.hs
plutus-pab-executables/plutus-pab-executables.cabal

Fixes two blocking issues for Marlowe:
1. The purescript generation now includes a bridge for  `ExportTx`, which was previously omitted. The closure of purescript types was incomplete without this.
2. `pab-executables.cabal` no longer contains a non-standard named library `plutus-pab-psgenerator`. The non-standard library name had prevented external use of the library via either `cabal` or `nix-build`. (Just renaming the library seemed preferable to renaming the folder. Note that the `cabal` version constraint did not allow non-standard library names.)
These changes were tested in https://github.com/input-output-hk/marlowe-cardano/pull/57. It was not possible to test fully in `plutus-apps` because `nix-build` in the root folder previously fails there.
- Branch
- PR

SCP-3216 psgenerator and PAB compatibility with Marlowe

---

default.nix
nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-pab-executables.nix
nix/pkgs/haskell/materialized-darwin/default.nix
nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-pab-executables.nix
nix/pkgs/haskell/materialized-linux/default.nix
nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-pab-executables.nix
nix/pkgs/haskell/materialized-windows/default.nix
plutus-pab-executables/README.md
plutus-pab-executables/demo/pab-nami/client/default.nix
plutus-pab-executables/demo/pab-nami/pab/app/Generator.hs
plutus-pab-executables/plutus-pab-executables.cabal

Fix #235.
Instead of providing a builtin PAB's psapigenerator, with #216 we encourage users to create their own small psapigenerators.
`pab-nami-demo-generator` is a small executable with only one purpose — to generate ps types for the `DemoContract`.
---
- Branch
- PR

Fix the problem with pab-nami-demo psapigenerator #235

---

README.adoc

According to Moritz this is bad advice and it's better to leave things
with the default settings (sandbox off).

Remove note about Nix sandbox on Macos

---

plutus-pab-executables/plutus-pab.yaml.sample
plutus-pab-executables/tx-inject/config.yaml
plutus-pab/src/Cardano/ChainIndex/Server.hs
plutus-pab/src/Cardano/Node/Client.hs
plutus-pab/src/Cardano/Node/Mock.hs
plutus-pab/src/Cardano/Node/Server.hs
plutus-pab/src/Cardano/Node/Types.hs
plutus-pab/src/Cardano/Wallet/Mock/Handlers.hs
plutus-pab/src/Cardano/Wallet/Mock/Server.hs
plutus-pab/src/Cardano/Wallet/Mock/Types.hs
plutus-pab/src/Plutus/PAB/App.hs
plutus-pab/src/Plutus/PAB/Run/Cli.hs
plutus-pab/src/Plutus/PAB/Types.hs

This fixes a couple of issues:
A. When starting all servers the mocked chain index and wallet are also started. However, they can only use the mocked versions of the client which requires a mocked server running. When these clients try to connect to the Alonzo node the versions don't match causing errors.
* Solution: I removed the mocked services from the list of commands to run if we are connecting to an alonzo node and added a list of services started to the command's output (to point out that we are not even trying to start those services in those circumstances).
B. When starting the PAB server the mocked chain is always used to synchronise the slot number, which causes the same connection errors when trying to connect to the alonzo node.
* Solution: I wrote a function that runs chain …

Fix protocol version error messages happening during synchronisation.

---

playground-common/src/PSGenerator/Common.hs
plutus-contract/src/Plutus/Contract/Wallet.hs
plutus-contract/src/Wallet/Emulator/Wallet.hs
plutus-ledger-constraints/src/Ledger/Constraints/OffChain.hs
plutus-pab-executables/demo/pab-nami/client/generated/Ledger/Constraints/OffChain.purs
plutus-playground-client/generated/Ledger/Constraints/OffChain.purs
plutus-use-cases/test/Spec/crowdfundingEmulatorTestOutput.txt

Prior to this commit, `Ledger.Constraints.Offchain.updateUtxoIndex` would discard lookups for inputs that aren't script outputs. However, sometimes it is necessary to include particular public-key `TxIn`s in a transaction, via `Plutus.Contract.Wallet.ExportTx.lookups`: a good example of this is when a `Plutus.Contract.Currency.OneShotCurrency` needs to consume a specified `UTxO` in its minting policy. Even though `Plutus.Constraints.Tx.mustSpendPubKeyOutput` adds a public-key input to the lookups, `updateUtxoIndex` discards that, with the result that it is only by chance that `cardano-wallet` would select that necessary input for the balanced transaction and provide it to Plutus validators. (Note that `cardano-wallet` does not automatically provide the `TxIn` in the partially constructed …

SCP-3305 SCP-3263 fixed Ledger.Constraints.Offchain.updateUtxoIndex

---

default.nix
nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-pab-executables.nix
nix/pkgs/haskell/materialized-darwin/default.nix
nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-pab-executables.nix
nix/pkgs/haskell/materialized-linux/default.nix
nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-pab-executables.nix
nix/pkgs/haskell/materialized-windows/default.nix
plutus-pab-executables/examples/ContractExample/PayToWallet.hs
plutus-pab-executables/pab-cli/App.hs
plutus-pab-executables/pab-cli/CommandParser.hs
plutus-pab-executables/pab-cli/Main.hs
plutus-pab-executables/pab-cli/README.md
plutus-pab-executables/pab-cli/Types.hs
plutus-pab-executables/plutus-pab-executables.cabal
plutus-pab/src/Cardano/Node/Types.hs
plutus-pab/src/Plutus/PAB/Types.hs
shell.nix

PAB CLI for easing the starting of components based on supported scenarios/use-cases.
Provides a `pab-cli` command line app in the `nix-shell`. This CLI can start the PAB in the currently supported scenarios (with mocked components, real components on mainnet or testnet, and optionally the cardano-wallet).
Also provides the `plutus-chain-index` executable in the `nix-shell`.
Next step is to integrate this tool in `plutus-starter`.
- Branch
- PR

SCP-3367: PAB CLI for easing the starting of PAB + components

---

plutus-use-cases/src/Plutus/Contracts/Uniswap/OnChain.hs

I've verified that **validateRemove** doesn't check the real **outA** and **outB**. It computes **outA** and **outB** with **calculateRemoval** and then check that both are greater than 0. The issue is that it doesn't check the real values of A and B in the output.
I've run the tests using the following malicious offchain code and the new constraint in **validateRemove**, resulting in a test failure (wallet balances don't match) due to a validator failure:  "_removal of invalid amount of tokens_".
```
-- | Removes some liquidity from a liquidity pool in exchange for liquidity tokens.
remove :: forall w s. Uniswap -> RemoveParams -> Contract w s Text ()
remove us RemoveParams{..} = do
(_, (oref, o, lp, liquidity)) <- findUniswapFactoryAndPool us rpCoinA rpCoinB
pkh …
```

plutus-use-cases-uniswap : validateRemove doesn't check real outA and outB

---

plutus-contract/src/Plutus/Contract/Test/ContractModel.hs
plutus-contract/src/Plutus/Contract/Test/ContractModel/Internal.hs
plutus-use-cases/test/Spec/GameStateMachine.hs
plutus-use-cases/test/Spec/Uniswap.hs

This adds the ability to assert properties directly in the `ContractModel` specifications.
- Branch
- PR

ContractModel: add assertSpec operation

---

nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-chain-index.nix
nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-chain-index.nix
nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-chain-index.nix
plutus-chain-index-core/src/Plutus/ChainIndex.hs
plutus-chain-index-core/src/Plutus/ChainIndex/Types.hs
plutus-chain-index/plutus-chain-index.cabal
plutus-chain-index/src/Plutus/ChainIndex/App.hs
plutus-chain-index/src/Plutus/ChainIndex/CommandLine.hs
plutus-chain-index/src/Plutus/ChainIndex/Config.hs
plutus-chain-index/src/Plutus/ChainIndex/Lib.hs
plutus-chain-index/src/Plutus/ChainIndex/Logging.hs
plutus-chain-index/src/Plutus/ChainIndex/SyncStats.hs
plutus-contract/test/Spec/golden/traceOutput - pubKeyTransactions.txt
plutus-contract/test/Spec/golden/traceOutput - pubKeyTransactions2.txt
plutus-contract/test/Spec/golden/traceOutput - wait1.txt
plutus-ledger/src/Ledger/Blockchain.hs

Summary of changes:
* Syncing message now logs every 30s
* Prints syncing percentage, number of applied blocks, number of rollbacks and current tip
* Logging uses the Trace for more consistent logging with PAB and cardano-node.
* Added warning flag for missing import list
Example of new chain-index logging (the number shown are not the actual values):
```
[chain-index:Warning:30] [2022-02-09 13:59:51.71 UTC] No synced blocks in the last 30s.
[chain-index:Info:30] [2022-02-09 13:59:54.71 UTC] Syncing (7.38%). Applied 7 blocks, 1 rollbacks in the last 30s. Current tip is Point(Slot 3898564, BlockId 93e58766e4ab743ea07d5f2a070cb9c3e7b95db160d04203c4764fb1050d422d)
[chain-index:Info:30] [2022-02-09 13:59:57.72 UTC] Syncing (7.38%). Applied 67 blocks, 0 rollbacks in the last 30s. Current tip …
```

SCP-3431: Better syncing logging in the chain-index.

---

plutus-contract/src/Plutus/Contract/Test/ContractModel.hs
plutus-contract/src/Plutus/Contract/Test/ContractModel/Internal.hs
plutus-contract/src/Plutus/Contract/Test/ContractModel/Symbolics.hs
plutus-use-cases/test/Spec/Auction.hs
plutus-use-cases/test/Spec/Escrow.hs
plutus-use-cases/test/Spec/GameStateMachine.hs
plutus-use-cases/test/Spec/Prism.hs
plutus-use-cases/test/Spec/SealedBidAuction.hs
plutus-use-cases/test/Spec/Uniswap.hs
plutus-use-cases/test/Spec/Vesting.hs

Some contracts, like the Uniswap example contract, have predictable overhead and rounding errors that prevent the strict NoLockedFunds property from passing. This PR introduces a little bit of wiggle room to allow for such contracts.
- Branch
- PR

ContractModel: Add wiggle room options to NoLockedFunds

---

plutus-ledger/src/Ledger/Orphans.hs

`DiffMilliSeconds` is a common type for endpoint parameters, having an orphan instance derived here would be quite convenient.
- Branch
- PR

Ledger Orphans: derive ToSchema for DiffMilliSeconds

---

plutus-pab/src/Plutus/PAB/Core/ContractInstance/BlockchainEnv.hs

PAB is logging too much in recent slots - making it impractical to run PAB on real networks.
---
- Branch
- PR

Make PAB log less in recent slots

---

plutus-pab/src/Cardano/Wallet/LocalClient.hs

The `Cardano.Wallet.LocalClient.runClient'` function erroneously rethrows errors it catches instead of returning them via `pure . Left`, as required by its type signature. The errors are not handled and end up killing the thread that handles the contract instance. This change successfully passes the Marlowe test https://github.com/input-output-hk/marlowe-cardano/blob/sprint-52/marlowe-cli/test/test-wallet-failure.yaml.
(In general, I recommend reviewing the PAB codebase for similar re-throwing problems and for `forkIO`s that aren't guarded against its thread dying because of an uncaught exception.)
- Branch
- PR

SCP-3331 Fixed error handling for transaction balancing in PAB.

---

nix/pkgs/haskell/haskell.nix

Fix `enableHaskellProfiling`. Doesn't work since https://github.com/input-output-hk/haskell.nix/commit/0e2ae928e296a68ec16adbed5e7d4f7dca815b14
- Branch
- PR

Change enableExecutableProfiling to enableProfiling

---

nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-chain-index.nix
nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-chain-index.nix
nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-chain-index.nix
plutus-chain-index/plutus-chain-index.cabal
plutus-chain-index/src/Control/Concurrent/STM/TBMQueue.hs
plutus-chain-index/src/Plutus/ChainIndex/App.hs
plutus-chain-index/src/Plutus/ChainIndex/CommandLine.hs
plutus-chain-index/src/Plutus/ChainIndex/Config.hs
plutus-chain-index/src/Plutus/ChainIndex/Events.hs
plutus-chain-index/src/Plutus/ChainIndex/Lib.hs

This should reduce the fluctuation of the memory usage of the chain-index.
- Branch
- PR

SCP-3680: Use the number of transactions instead of number of blocks for queue.

---

plutus-pab/test-node/testnet/chain-index-config.json

Add the "cicAppendTransactionQueueSize" field to the chain index config so that parsing succeeds.
Use a value from the default config.
- Branch
- PR

Add "cicAppendTransactionQueueSize" to config

---

plutus-chain-index-core/src/Plutus/ChainIndex/Handlers.hs

Fix for the utxo-with-currency query of the chain-index that was returning spent utxos. Problem and solution, strongly related to #124 and #185.
- Branch
- PR

[plutus-chain-index-core]: fix utxo-with-currency beam query. Solution related with #185

---

plutus-chain-index-core/src/Plutus/ChainIndex/Api.hs
plutus-chain-index-core/src/Plutus/ChainIndex/Client.hs
plutus-chain-index-core/src/Plutus/ChainIndex/DbSchema.hs
plutus-chain-index-core/src/Plutus/ChainIndex/Effects.hs
plutus-chain-index-core/src/Plutus/ChainIndex/Emulator/DiskState.hs
plutus-chain-index-core/src/Plutus/ChainIndex/Emulator/Handlers.hs
plutus-chain-index-core/src/Plutus/ChainIndex/Handlers.hs
plutus-chain-index-core/src/Plutus/ChainIndex/Server.hs
plutus-chain-index-core/src/Plutus/ChainIndex/Types.hs
plutus-chain-index-core/test/Plutus/ChainIndex/Emulator/HandlersSpec.hs
plutus-chain-index-core/test/Plutus/ChainIndex/HandlersSpec.hs
plutus-contract/src/Plutus/Contract.hs
plutus-contract/src/Plutus/Contract/Effects.hs
plutus-contract/src/Plutus/Contract/Request.hs
plutus-contract/src/Plutus/Contract/Trace/RequestHandler.hs
plutus-pab-executables/demo/pab-nami/client/generated/Plutus/Contract/Effects.purs
plutus-pab/src/Plutus/PAB/Simulator.hs
plutus-playground-client/generated/Plutus/Contract/Effects.purs

Reintegrate the chain-index queries for querying txs by id and spent tx outputs from reference.
These were removed in a previous PR. However, a lot of downstream users were dependent on those. Thus, this PR reintegrates them, although it will probably make syncing slower. This is acceptable for the time being as we're working towards a configurable chain-index in the future.
- Branch
- PR

Reintegrate the chain-index queries for querying txs by id and spent tx outputs from reference

---

plutus-contract/src/Plutus/Contract/Wallet.hs
plutus-contract/src/Wallet/Emulator/Wallet.hs
plutus-ledger-constraints/src/Ledger/Constraints/OffChain.hs
plutus-pab-executables/demo/pab-nami/client/generated/Ledger/Constraints/OffChain.purs
plutus-playground-client/generated/Ledger/Constraints/OffChain.purs

The `PaymentPubKey` in the `ScriptLookups` is unnecessary for actually signing a transaction. 
Removed it.
- Branch
- PR

Remove unnecessary/unused PaymentPubKey from ScriptLookups in plutus-ledger-constraints

---

plutus-contract/src/Plutus/Contract/Typed/Tx.hs
plutus-ledger-constraints/src/Ledger/Constraints.hs
plutus-ledger-constraints/src/Ledger/Constraints/TxConstraints.hs

The `addTxIn` is defined in a way to mostly be used as an accumulator in a fold. Better way is to simply define it as a smart constructor for creating a constraint, and constraints can be combined using the Semigroup instances.
- Branch
- PR

Replaced the addTxIn constraint with mustSpendOutputFromTheScript

---

plutus-contract/src/Wallet/Emulator/Wallet.hs
plutus-ledger/plutus-ledger.cabal
plutus-ledger/src/Ledger/CardanoWallet.hs
plutus-pab/src/Cardano/Wallet/Mock/Handlers.hs

Avoid depending on cardano-wallet-core in `plutus-ledger` to make downstream consumption of only that package easier.
This would help at least us over at https://github.com/input-output-hk/hydra-poc as we are not using anything else from `plutus-apps` right now.
Maybe this does not make sense as you will be adding more wallet-related things to `plutus-ledger`.
We may be able to refactor / vendor out the relevant usage of `plutus-ledger` alltogether.

Have plutus-ledger not depend on cardano-wallet-core

---

cabal.project
doc/plutus/tutorials/Auction.hs
doc/plutus/tutorials/Escrow5.hs
doc/plutus/tutorials/Escrow6.hs
nix/pkgs/haskell/sha256map.nix
plutus-contract-certification/src/Plutus/Contract/Test/Certification/Run.hs
plutus-contract/plutus-contract.cabal
plutus-contract/src/Plutus/Contract/Test.hs
plutus-contract/src/Plutus/Contract/Test/ContractModel/Internal.hs
plutus-contract/src/Plutus/Contract/Test/Coverage.hs
plutus-contract/src/Plutus/Contract/Test/Coverage/Analysis.hs
plutus-contract/src/Plutus/Contract/Test/Coverage/Analysis/Common.hs
plutus-contract/src/Plutus/Contract/Test/Coverage/Analysis/DeBruijn.hs
plutus-contract/src/Plutus/Contract/Test/Coverage/Analysis/Interpreter.hs
plutus-contract/src/Plutus/Contract/Test/Coverage/Analysis/Pretty.hs
plutus-contract/src/Plutus/Contract/Test/Coverage/Analysis/Types.hs
plutus-contract/src/Plutus/Contract/Test/Coverage/ReportCoverage.hs
plutus-use-cases/plutus-use-cases.cabal
plutus-use-cases/src/Plutus/Contracts/GameStateMachine.hs
plutus-use-cases/src/Plutus/Contracts/GameStateMachine/Coverage.hs
plutus-use-cases/src/Plutus/Contracts/Uniswap/OffChain.hs
plutus-use-cases/src/Plutus/Contracts/Uniswap/Pool.hs
plutus-use-cases/test/Spec/Auction.hs
plutus-use-cases/test/Spec/GameStateMachine.hs
plutus-use-cases/test/Spec/Tutorial/Escrow.hs
plutus-use-cases/test/Spec/Tutorial/Escrow5.hs
plutus-use-cases/test/Spec/Tutorial/Escrow6.hs
plutus-use-cases/test/Spec/Uniswap.hs
plutus-use-cases/test/Spec/renderGuess.txt

This PR introduces a tool that finds program locations in validators whose exectution always lead to validator failure. Separating out such locations greatly improves the readability of coverage reports.
This PR does not include the extensive test-suite comprised of QuickCheck tests that we've used to validate the analysis (c.f. branch `Coverage-static-analysis` on the Quviq fork of this repo) as we are in the process of moving the generators to the plutus-core repo.
The tests will come in a separate PR later.
- Branch
- PR

Coverage static analysis

---

plutus-chain-index/src/Plutus/ChainIndex/App.hs

Pr adds a new definition `Plutus.ChainIndex.App (runMainWithLog)` allowing to run chain-index with different function to do startup logs and refactors `runMain` to use this definition. This is a tiny commit.
In [plutip](https://github.com/mlabs-haskell/plutip/issues/48) - a tool to spin up a testnet and run contracts - we call **chain-index**'s main function (from code with `runMain`) as one of the components. It does logging at startup to stdout and these logs get mixed up with the rest of the logs. Running it in a new process is troublesome, so I am asking if I could just add this small change to chain-index itself.

Allow chain-index to print silently.

---

plutus-pab/src/Plutus/PAB/Core.hs

Export all the content of PABEnvironment so that other alternative monads may orchestrate the execution of DApp applications and smart contracts and yet make use of the native monad to invoke PAB primitives for managing smart contracts etc.
Example of usage in https://github.com/agocorona/DAppFlow/blob/main/pabtest.hs#L227-L238
For that purpose, the alternative monad need to store and set the entire PABEnvironment before invoking such primitives. so all the PABEnvironment should be reachable externally to get/set his value
- Branch
- PR

Export full PABEnvironment

---

plutus-contract/src/Wallet/Emulator/Wallet.hs
plutus-contract/test/Spec/Contract.hs
plutus-contract/test/Spec/golden/traceOutput - pubKeyTransactions.txt
plutus-contract/test/Spec/golden/traceOutput - pubKeyTransactions2.txt
plutus-use-cases/test/Spec/crowdfundingEmulatorTestOutput.txt
plutus-use-cases/test/Spec/renderCrowdfunding.txt
plutus-use-cases/test/Spec/renderGuess.txt
plutus-use-cases/test/Spec/renderVesting.txt

plutus-contract emulator: Modifying addOutputs to replicate what cardano-wallet and cardano-node do, i.e., new outputs due to balancing are append to the list and not prepend.
Cherry-picked commit from:  https://github.com/etiennejf/plutus-apps/commit/27bbb47cd463b4054daadda40f31a9abaaaf2288
- Branch
- PR

plutus-contract: Modifying addOutputs in emulator

---

quickcheck-dynamic/src/Test/QuickCheck/DynamicLogic.hs
quickcheck-dynamic/src/Test/QuickCheck/StateModel.hs

This solves an issue the hydra team were having with building a StateModel that depends on IOSim.
- Branch
- PR

QuickCheck-dynamic: Move Typeable constraint further downstream of class hierarchy

---

plutus-streaming/src/Plutus/Streaming.hs

As per internal discussion.
This a parameter needed only for the Byron era. Since the Byron era is over and the parameter has never changed it is ok to hardcode this.

PLT-381 Fix the value of epochSlots and add a comment

---

plutus-streaming/src/Plutus/Streaming.hs

Someone made me notice that I was using an unbounded tchan where I could get away with a mvar. Basically I want to have the two threads (the one running chain-sync and the stream consumer) in lock-step.
In the current version, blocks are pushed in the channel at full speed independently from the speed at which they are consumed, this can cause memory issues if the consumer is slower than the network (which is likely).

PLT-380 Replace TChan with bounded queue

---

scripts/upload-event-dump.sh
shell.nix

This script is invoked after generating each event dump file. It compresses the file, uploads it to S3, deletes the local copy, and cleans up old checkpoint files.

PLT-333: Script for uploading an event dump file to S3

---

plutus-use-cases/src/Plutus/Contracts/Auction.hs

Using a single `derivingVar` line for `Semigroup` and `Monoid`. (Good for smart contracts template)
- Branch
- PR

Use one derivingVar line

---

plutus-chain-index-core/src/Plutus/ChainIndex/Emulator/Handlers.hs
plutus-contract/src/Plutus/Trace/Scheduler.hs
plutus-contract/test/Spec/golden/traceOutput - pubKeyTransactions.txt
plutus-contract/test/Spec/golden/traceOutput - pubKeyTransactions2.txt
plutus-contract/test/Spec/golden/traceOutput - wait1.txt

Should fix #318.
This reduces the memory consumption from 3gb to under 300mb (approximately) for me with this test:
```
run "test"
(walletFundsChange w1 mempty
.&&. walletFundsChange w2 mempty
.&&. walletFundsChange w3 mempty) (void $ Trace.waitUntilSlot 100000)
```
- Branch
- PR

[emulator]: fix waitUntilSlot memory consumption

---

plutus-streaming/plutus-streaming.cabal

Fixes haskell.nix build when depending on plutus-apps.
Otherwise it fails with an error about missing `CHANGELOG.md`.
Alternatively close this PR and add missing `CHANGELOG.md` file.
cc @andreabedini 
- Branch
- PR

Remove reference to non-existing CHANGELOG for `plutus-streaming`

---

shell.nix

- Enforced `LC_ALL=C.utf8` in the nix-shell to avoid encoding problems on hosts with non-utf8 locales.

PLT-502 Add locale `LC_ALL=C.utf8` to nix shell

---

plutus-contract/src/Plutus/Contract/Test.hs

It is not obvious that the `initialChainState` of the `CheckOptions` will come from the generator model. I would have benefitted from seeing this note attached to the function.
- Branch
- PR

Add note to `checkPredicateGenOptions`

---

plutus-example/app/create-script-context.hs
plutus-example/app/plutus-example.hs
plutus-example/plutus-example.cabal
plutus-example/src/PlutusExample/PlutusVersion1/RedeemerContextScripts.hs
plutus-example/src/PlutusExample/PlutusVersion2/RedeemerContextEquivalence.hs
plutus-example/src/PlutusExample/ScriptContextChecker.hs

Note:
- The mint field is still not tested
- Withdrawals are not tested
- When we feed a validity range via the redeemer we get failures when we try to compare for equality ((==) and (/=)) with the validity interval in the script context.

Add script equivalence context test for the V2 context.

---

doc/plutus/tutorials/EscrowImpl.hs
plutus-chain-index-core/src/Plutus/ChainIndex/Tx.hs
plutus-chain-index/app/Marconi.hs
plutus-chain-index/app/Marconi/Index/Datum.hs
plutus-chain-index/plutus-chain-index.cabal
plutus-contract/src/Plutus/Contract/Oracle.hs
plutus-contract/src/Plutus/Contract/Test/ContractModel/DoubleSatisfaction.hs
plutus-contract/test/Spec/Contract.hs
plutus-ledger-constraints/src/Ledger/Constraints/OffChain.hs
plutus-ledger/src/Ledger/Index.hs
plutus-ledger/src/Ledger/Tx.hs
plutus-ledger/src/Ledger/Tx/CardanoAPI.hs
plutus-script-utils/plutus-script-utils.cabal
plutus-script-utils/src/Plutus/Script/Utils/Scripts.hs
plutus-script-utils/src/Plutus/Script/Utils/V1/Scripts.hs
plutus-script-utils/src/Plutus/Script/Utils/V1/Typed/Scripts.hs
plutus-script-utils/src/Plutus/Script/Utils/V1/Typed/Scripts/Validators.hs
plutus-use-cases/src/Plutus/Contracts/Escrow.hs
plutus-use-cases/src/Plutus/Contracts/Tutorial/Escrow.hs
plutus-use-cases/src/Plutus/Contracts/Tutorial/EscrowStrict.hs
plutus-use-cases/test/Spec/Escrow/Endpoints.hs

Moved datum and redeemer hash computation functions in plutus-script-utils in another module which does not depend on a specific version of Plutus.
- Branch
- PR

Moved datum and redeemer hash computation functions in plutus-script-utils

---

plutus-contract/src/Plutus/Contract.hs
plutus-contract/src/Plutus/Contract/Effects.hs
plutus-contract/src/Plutus/Contract/Request.hs
plutus-contract/src/Plutus/Contract/Trace.hs
plutus-contract/src/Plutus/Contract/Trace/RequestHandler.hs
plutus-contract/src/Plutus/Trace/Emulator/ContractInstance.hs
plutus-pab/src/Plutus/PAB/Arbitrary.hs
plutus-pab/src/Plutus/PAB/Core/ContractInstance.hs
plutus-use-cases/src/Plutus/Contracts/PubKey.hs

- Deprecates 'currentSlot' contract method.
- Introduces 'currentPABSlot' - a replacement for 'currentSlot'.
- Introduces 'currentChainIndexSlot' to query the chain index's node's slot.
- Branch
- PR

PLT-309: Rename 'currentSlot' to 'currentPABSlot' and add 'currentChainIndexSlot'.

---

plutus-example/app/plutus-example.hs
plutus-example/src/PlutusExample/PlutusVersion2/RedeemerContextEquivalence.hs
plutus-example/src/PlutusExample/ScriptContextChecker.hs

Add a Plutus script that checks that the mint field of the ScriptContext is equal to the mint field of our redeemer
- Branch
- PR

Add minting context equivalence test plutus script

---

plutus-streaming/src/Plutus/Streaming.hs

The missing field prevented running marconi on testnet against a local node.
The bash shebang fix is just a minor fix. Nixos doesn't have a `/bin/bash`, but `/usr/bin/env bash` seems to be supported on all unixes so switch to that (in the entire repo, not sure if that's ok).
- Branch
- PR

Add missing field

---

plutus-ledger-constraints/src/Ledger/Constraints/OnChain/V1.hs
plutus-use-cases/test/Spec/renderGuess.txt

Returning `True` in an `any` function meant that the check would succeed if there was any other output.
- Branch
- PR

Fix onchain MustPayToPubKeyAddress check

---

plutus-ledger-constraints/src/Ledger/Constraints/TxConstraints.hs

Made the functions `Ledger.Constraints.TxConstraints.collectFromPlutusV1ScriptFilter` and `Ledger.Constraints.TxConstraints.collectFromTheScript` as unrelated functions.
The rationale is that if someone uses `collectFromPlutusV1ScriptFilter`,
the constraints will fail with a `TypedValidatorMissing` error for
lookups, even though we're not using typed validators.
This fix was triggered by #641 
- Branch
- PR

Fix Ledger.Constraints.TxConstraints.collectFromPlutusV1ScriptFilter implementation

---

playground-common/src/PSGenerator/Common.hs
playground-common/src/Schema.hs
plutus-contract/test/Spec/Emulator.hs
plutus-ledger-constraints/src/Ledger/Constraints/OffChain.hs
plutus-ledger/src/Ledger/Index.hs
plutus-ledger/src/Ledger/Orphans.hs
plutus-ledger/src/Ledger/Tx/CardanoAPI.hs
plutus-ledger/src/Ledger/Tx/Internal.hs
plutus-ledger/src/Ledger/Typed/Scripts.hs
plutus-pab/src/Plutus/PAB/Arbitrary.hs

@michaelpj said we shouldn't be using `LedgerPlutusVersion`. We can use `Cardano.Ledger.Alonzo.Language` instead.
- Branch
- PR

Replace LedgerPlutusVersion with Language type

---

plutus-contract/src/Plutus/Contract/Wallet.hs
plutus-contract/src/Wallet/Emulator/Wallet.hs
plutus-contract/test/Spec/TxConstraints/TimeValidity.hs
plutus-ledger-constraints/src/Ledger/Constraints/OffChain.hs
plutus-tx-constraints/src/Ledger/Tx/Constraints/OffChain.hs
plutus-tx-constraints/test/Spec.hs

\[WIP] The tests part is still missing but the validityRanges are now directly store in the Tx, not in an extra field.   
- Branch
- PR

PLT-670 Add  MustValidateIn to tx constraints

---

plutus-contract-certification/src/Plutus/Contract/Test/Certification/Run.hs

You can pass an optional `Control.Concurrent.Chan` in the certification options to get events when tests pass or fail.
- Branch
- PR

Add event channel to certification function

---

plutus-chain-index-core/src/Plutus/ChainIndex/Client.hs

This PR brings back export of getUnspentTxOutsAtAddress to Plutus.ChainIndex.Client module.
We are using plutus-chain-index-core in our application and it would be great to have getUnspentTxOutsAtAddress back.
- Branch
- PR

export `getUnspentTxOutsAtAddress`

---

plutus-chain-index-core/plutus-chain-index-core.cabal
plutus-chain-index-core/src/Marconi/Index/ScriptTx.hs
plutus-chain-index-core/src/Marconi/Index/Utxo.hs
plutus-chain-index-core/src/Plutus/Contract/CardanoAPI.hs
plutus-chain-index-core/test/MarconiSpec.hs
plutus-chain-index-core/test/Spec.hs
plutus-chain-index/app/Marconi.hs
plutus-ledger/src/Ledger/Tx/CardanoAPI.hs

This is a draft PR for the jira issue [marconi indexer: transactions that have been issued to a particular script](https://input-output.atlassian.net/browse/PLT-172). (This PR is also wrongly based off of `next-node` branch because it can understand the blocks since Vasil hard-fork -- will rebase once I manage to resolve the issues below.)
A concrete code thing I need help with is extracting script hashes from a transaction [here](https://github.com/input-output-hk/plutus-apps/blob/9a2e24eb1de814c33d42c7b2ecc11e8e62620361/plutus-chain-index/app/Marconi.hs#L261): how/where would I find the type(s)?
Another question is that the Jira issue says to set script address as the primary key, but if this is an index from transaction to script, then this is an 1:n relationship because (as far as I …

PLT-172: Marconi index transactions that have been issued to a particular script

---

flake.lock
marconi/README.md

By upgrading `gitignore-nix` (which includes the relevant fix via https://github.com/hercules-ci/gitignore.nix/pull/58), we can now use flakes to build Marconi in pure mode (i.e. without the `--impure` flag).
Also see our related PR https://github.com/input-output-hk/plutus-apps/pull/702
Tested locally with 
`nix build .#marconi` 
And with 
`nix build github:input-output-hk/plutus-apps/7f45669dfe4b9e5440d0d9c74eea18b2104eb7f0#marconi`

Upgrade gitignore-nix version

---

plutus-contract-certification/src/Plutus/Contract/Test/Certification/Run.hs

Chan has no built-in closing mechanism, relying instead on BlockedIndefinitelyOnMVar to signal that no new messages are coming. Unfortunately, due to
https://gitlab.haskell.org/ghc/ghc/-/issues/18370, any thread using this mechanism to detect end-of-channel will not be able to reliably signal other threads of later work. So we use an application-level end-of-channel signal instead.

certification: Send CertificationDone event when finished running.

---

plutus-contract/test/Spec/TxConstraints/MustSpendScriptOutput.hs
plutus-ledger-constraints/src/Ledger/Constraints/OnChain/V2.hs
plutus-ledger/src/Ledger/Test.hs

- Improved onchain Redeemer check for MustSpendScriptOutput and MustSpendScriptOutputWithMatchingDatumAndValue constraints
- Fixed some MustSpendScriptOutput constraint tests that were reporting false-positives
- Added additional scenarios including V2 scripts in tests for checking Redeemer with MustSpendScriptOutput
- Using versioned minting policies instead of validators for MustSpendScriptOutput tests

Fix some false-positives MustSpendScriptOutput tests using versioned minting policies

---

plutus-contract/test/Spec.hs
plutus-contract/test/Spec/TxConstraints/MustProduceAtLeast.hs
plutus-contract/test/Spec/TxConstraints/MustSpendPubKeyOutput.hs
plutus-ledger-constraints/src/Ledger/Constraints/OffChain.hs
plutus-script-utils/src/Plutus/Script/Utils/V1/Typed/Scripts/Validators.hs

`MustPayToTheScript` didn't add the datum to the `Tx`
- Branch
- PR

PLT-1036 Fix failing test suites after the main/next-node merge

---

plutus-ledger/src/Ledger/Tx.hs
plutus-use-cases/test/Spec/crowdfundingEmulatorTestOutput.txt

Fix Ledger.Tx.getCardanoTxData so that the cardano-api transactions returns all the datums of the TxBody, including the datums of the Plutus scripts.
- Branch
- PR

Fix Ledger.Tx.getCardanoTxData

---

plutus-chain-index/src/Plutus/ChainIndex/App.hs
plutus-chain-index/src/Plutus/ChainIndex/Lib.hs

This patch explicitly considers the `ChainTipAtGenesis` case in `getTipSlo`t so as to avoid a pattern matching error whenever the chain-index is trying to sync with a local node that is still at genesis tip.
If this happens then chain-index will exit with an appropriate failure message.

Considering ChainTipAtGenesis case in getTipSlot

---

doc/adr/0013-tx-validity-time-range-fix.rst
doc/adr/index.rst

PLT-1034 Proposing an ADR to modify the `MustValidateIn` constraint in `plutus-ledger-constraints` so that it can work with slots instead of POSIXTime.
The link to the ADR is here: https://plutus-apps--781.org.readthedocs.build/en/781/adr/0013-tx-validity-time-range-upper-bound.html
- Branch
- PR

PLT-1034 Proposing an ADR to modify the `MustValidateIn` constraint

---

plutus-contract/test/Spec/TxConstraints/MustSpendPubKeyOutput.hs
plutus-ledger-constraints/src/Ledger/Constraints/OffChain.hs
plutus-ledger-constraints/src/Ledger/Constraints/TxConstraints.hs
plutus-ledger-constraints/test/Spec.hs
plutus-tx-constraints/src/Ledger/Tx/Constraints/OffChain.hs

Throw errors if we try to use different redeemer or different reference script in different MustSpend, ignore all but one constraint otherwise.
- Branch
- PR

PLT-989 Improve behaviour of duplicated `MustSpend`

---

plutus-pab-executables/demo/pab-nami/pab/plutus-pab.yaml
plutus-pab-executables/plutus-pab.yaml.sample
plutus-pab/src/Plutus/PAB/App.hs
plutus-pab/src/Plutus/PAB/Core.hs
plutus-pab/src/Plutus/PAB/Simulator.hs
plutus-pab/src/Plutus/PAB/Timeout.hs
plutus-pab/src/Plutus/PAB/Types.hs
plutus-pab/test-node/testnet/pab-config.yml

Cherry-picked commits:
* https://github.com/etiennejf/plutus-apps/commit/e1ce0ef32ae6354950b807121f2dc96a769c5084
* https://github.com/etiennejf/plutus-apps/commit/2b484001a3d6b4b34bbcc0df308fb2ac422f7983
* https://github.com/etiennejf/plutus-apps/commit/ca9a3b9ccbe5fd578b790014a444aa993dfdea05
Summary:
* 'Plutus.PAB.Core.waitForInstanceState' now waits for a user-specified amount of time
* Bug fix in 'Plutus.PAB.Timeout'
* Modified the PAB configuration file to allow users to set the timeout value
cc @etiennejf 
- Branch
- PR

Adding a specifc timeout option for 'Plutus.PAB.Core.waitForInstanceState

---

plutus-pab-executables/test/full/Plutus/PAB/CoreSpec.hs
plutus-pab/src/Cardano/Wallet/RemoteClient.hs
plutus-pab/src/Control/Concurrent/STM/Extras/Stream.hs
plutus-pab/src/Plutus/PAB/App.hs
plutus-pab/src/Plutus/PAB/Core.hs
plutus-pab/src/Plutus/PAB/Core/ContractInstance.hs
plutus-pab/src/Plutus/PAB/Core/ContractInstance/BlockchainEnv.hs
plutus-pab/src/Plutus/PAB/Core/ContractInstance/STM.hs
plutus-pab/src/Plutus/PAB/Db/Memory/ContractStore.hs
plutus-pab/src/Plutus/PAB/Simulator.hs
plutus-pab/src/Plutus/PAB/Webserver/WebSocket.hs
plutus-pab/test/light/Cardano/Wallet/RemoteClientSpec.hs

* https://github.com/etiennejf/plutus-apps/commit/b8d01a8702f34c23c28cda4f59600e05f4ad3588
* https://github.com/etiennejf/plutus-apps/commit/e45f6b82ea956d88992f615551302128f600874c
Summary:
This avoids bottleneck when updating InMemInstances, especially when an instance already exists. PutState of InMemInstances is adjusted so as to avoid full map update when instance already exists.
cc @etiennejf 
- Branch
- PR

Change contractState and instancesState to mutable variables.

---

plutus-pab/src/Plutus/PAB/Core.hs
plutus-pab/src/Plutus/PAB/Db/Beam/ContractStore.hs
plutus-pab/src/Plutus/PAB/Db/Memory/ContractStore.hs
plutus-pab/src/Plutus/PAB/Effects/Contract.hs
plutus-pab/src/Plutus/PAB/Simulator.hs

* https://github.com/etiennejf/plutus-apps/commit/ab7b05a2b4db8e4f86470b75bb35fcd29b17b27c
* https://github.com/etiennejf/plutus-apps/commit/09bd551c7a0ecdb7c742f8cc16c83e2e9bc2a6a3
Summary:
Added the 'Contract.DeleteState' effect in Plutus.PAB.Effects.ContractStore and call it in Plutus.PAB.Core.stopInstance so that the state is deleted when the contract instance is done.
CC @etiennejf 
- Branch
- PR

Added the 'Contract.DeleteState' effect in PAB and call it when an instance is stopped

---

pab-blockfrost/pab-blockfrost.cabal
pab-blockfrost/src/Plutus/Blockfrost/Client.hs
pab-blockfrost/src/Plutus/Blockfrost/Queries.hs
pab-blockfrost/src/Plutus/Blockfrost/Responses.hs
plutus-chain-index-core/src/Plutus/ChainIndex/Api.hs
plutus-chain-index-core/src/Plutus/ChainIndex/Client.hs
plutus-chain-index-core/src/Plutus/ChainIndex/DbSchema.hs
plutus-chain-index-core/src/Plutus/ChainIndex/Effects.hs
plutus-chain-index-core/src/Plutus/ChainIndex/Emulator/Handlers.hs
plutus-chain-index-core/src/Plutus/ChainIndex/Handlers.hs
plutus-chain-index-core/src/Plutus/ChainIndex/Server.hs
plutus-contract/src/Plutus/Contract.hs
plutus-contract/src/Plutus/Contract/Effects.hs
plutus-contract/src/Plutus/Contract/Request.hs
plutus-contract/src/Plutus/Contract/Trace/RequestHandler.hs
plutus-pab/src/Plutus/PAB/Simulator.hs

*  https://github.com/etiennejf/plutus-apps/commit/6f827e1d5596adc52d94de38162600156567af31
*  https://github.com/etiennejf/plutus-apps/commit/e19627cbcac23190b1cdcbf350be5bdfb8137e4f
*  https://github.com/etiennejf/plutus-apps/commit/4fddda6273a77ba6d0ee2e81d16426b89537667f
*  https://github.com/etiennejf/plutus-apps/commit/ec541ad66a956dcf33894b9278562f6e7c3f2480
Summary:
* Added `Plutus.Contract.Request.datumsAt` which returns all datums associated with a target address
* Added datum in address row of plutus-chain-index DbSchema to avoid recording transaction in db and facilitate retrival and added datumsAtAddress query
* Added DatumAtAddress query to pab-blockfrost
CC @etiennejf 
- Branch
- PR

Adding datumsAt contract request query

---

plutus-contract/test/Spec/Contract/Tx/Constraints/MustPayToOtherScript.hs
plutus-ledger-constraints/src/Ledger/Constraints/OnChain/V1.hs
plutus-ledger-constraints/src/Ledger/Constraints/OnChain/V2.hs
plutus-ledger-constraints/src/Ledger/Constraints/TxConstraints.hs
plutus-use-cases/test/Spec/renderGuess.txt

We were making an exact comparison for non-ada values while we must have checked that the provided values of the tx cover the expectations of the constraint.
I added a test for partial spending of other tokens. 
While at it, I refactored the `MustPayToOtherScript` test suite to harmonise it with the other constraints suites.
- Branch
- PR

PLT-885 fix a bug in onchain MustPayToOtherScript

---

plutus-example/app/plutus-example.hs
plutus-example/plutus-example.cabal
plutus-example/src/PlutusExample/PlutusVersion2/EcdsaSecp256k1Loop.hs
plutus-example/src/PlutusExample/PlutusVersion2/SchnorrSecp256k1Loop.hs

Two new plutus V2 scripts for looping over SECP256k1 ECDSA and Schnorr verify builtin functions.
Can use the following redeemers (cli json format). Change the `int` for number of loops:
ECDSA
```
{"constructor":0,"fields":[{"int":10},{"bytes":"0392d7b94bc6a11c335a043ee1ff326b6eacee6230d3685861cd62bce350a172e0"},{"bytes":"16e0bf1f85594a11e75030981c0b670370b3ad83a43f49ae58a2fd6f6513cde9"},{"bytes":"5fb12954b28be6456feb080cfb8467b6f5677f62eb9ad231de7a575f4b6857512754fb5ef7e0e60e270832e7bb0e2f0dc271012fa9c46c02504aa0e798be6295"}]}
```
Schnorr
```
{"constructor":0,"fields":[{"int":10},{"bytes":"599de3e582e2a3779208a210dfeae8f330b9af00a47a7fb22e9bb8ef596f301b"},{"bytes":"303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030 …
```

Add SECP256k1 ECDSA and Schnorr loop becnhmarking scripts

---

doc/plutus/tutorials/GameModel.hs
playground-common/src/Schema.hs
plutus-contract/test/Spec/Contract/Tx/Constraints/MustProduceAtLeast.hs
plutus-contract/test/Spec/Contract/Tx/Constraints/MustSpendAtLeast.hs
plutus-contract/test/Spec/Contract/Tx/Constraints/MustSpendPubKeyOutput.hs
plutus-ledger-constraints/src/Ledger/Constraints/OffChain.hs
plutus-ledger-constraints/src/Ledger/Constraints/TxConstraints.hs
plutus-ledger/src/Ledger/Address.hs
plutus-ledger/src/Ledger/Address/Orphans.hs
plutus-ledger/src/Ledger/Credential/Orphans.hs
plutus-ledger/src/Ledger/Crypto/Orphans.hs
plutus-ledger/src/Ledger/Orphans.hs
plutus-ledger/src/Ledger/Scripts/Orphans.hs
plutus-pab-executables/test/full/Plutus/PAB/CoreSpec.hs
plutus-tx-constraints/src/Ledger/Tx/Constraints/OffChain.hs
plutus-use-cases/src/Plutus/Contracts/GameStateMachine.hs
plutus-use-cases/src/Plutus/Contracts/Governance.hs
plutus-use-cases/src/Plutus/Contracts/Prism/Mirror.hs
plutus-use-cases/src/Plutus/Contracts/Uniswap/OffChain.hs
plutus-use-cases/test/Spec/GameStateMachine.hs
plutus-use-cases/test/Spec/Governance.hs
plutus-use-cases/test/Spec/Uniswap/Endpoints.hs
plutus-use-cases/test/Spec/renderGuess.txt

Offchain use of `MustProduceAtLeast` and `MustSpendAtLeast` now checks if we have produced/spent at least the given amount when we create the Tx, and throw an error if it isn't the case. (see PLT-665 for the rationale behind this change)
- Branch
- PR

PLT-1219 Remove offchain logic for MustProduceAtLeast and MustSpendAtLeast

---

cabal.project

I should have notices this earlier. It looks like we don't need this and everything supports aeson 2 (and have for a while).

Drop hw-aeson fork

---

plutus-example/src/PlutusExample/PlutusVersion2/EcdsaSecp256k1Loop.hs
plutus-example/src/PlutusExample/PlutusVersion2/SchnorrSecp256k1Loop.hs

Two new plutus V2 scripts for looping over SECP256k1 ECDSA and Schnorr verify builtin functions.
Can use the following redeemers (cli json format) to loop 10 times. Change the `int` for number of loops:
ECDSA
```
{"constructor":0,"fields":[{"int":1000010},{"bytes":"0392d7b94bc6a11c335a043ee1ff326b6eacee6230d3685861cd62bce350a172e0"},{"bytes":"16e0bf1f85594a11e75030981c0b670370b3ad83a43f49ae58a2fd6f6513cde9"},{"bytes":"5fb12954b28be6456feb080cfb8467b6f5677f62eb9ad231de7a575f4b6857512754fb5ef7e0e60e270832e7bb0e2f0dc271012fa9c46c02504aa0e798be6295"}]}
```
Schnorr
```
{"constructor":0,"fields":[{"int":1000010},{"bytes":"599de3e582e2a3779208a210dfeae8f330b9af00a47a7fb22e9bb8ef596f301b"},{"bytes":"303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303 …
```

Change secp256k1 loop scripts to have consistent counter value bitsizes

---

plutus-contract/src/Plutus/Contract/Test.hs
plutus-contract/src/Plutus/Contract/Wallet.hs
plutus-contract/src/Wallet/Emulator/Folds.hs
plutus-contract/src/Wallet/Emulator/Wallet.hs
plutus-contract/test/Spec/Contract/Tx/Constraints/RequiredSigner.hs
plutus-ledger-constraints/src/Ledger/Constraints/OffChain.hs
plutus-ledger/src/Ledger/Tx.hs
plutus-ledger/src/Ledger/Validation.hs
plutus-tx-constraints/src/Ledger/Tx/Constraints.hs
plutus-tx-constraints/src/Ledger/Tx/Constraints/OffChain.hs

Implementation details:
As we put the required signatures directly in the Tx, we don't need `unbalancedRequiredSignatories` in the unbalanced cardano Tx, so it's now removed.
- Branch
- PR

PLT-671 implement MustBeSignedBy for cardano TX

---

nix/pkgs/default.nix

It doesn't work on new Nixes due to trying to hit ~/.gitconfig.
Fixes flake evaluation.

Don't run gitignore-nix in pure-eval mode.

---

plutus-contract/changelog.d/20221128_060044_konstantinos.lambrou_minting_policy_antipattern.md
plutus-contract/src/Plutus/Contract/StateMachine/ThreadToken.hs
plutus-ledger/src/Ledger/Value.hs
plutus-use-cases/test/Spec/renderGuess.txt

Fix minting policy in tutorial and for state machine thread tokens in light of https://www.tweag.io/blog/2022-03-25-minswap-lp-vulnerability
* Added currentValueOf function in `Ledger.Value`
* Modified the StateMachine thread token
Co-authored-by: David Eichmann <EichmannD@gmail.com>
This PR comes partly from https://github.com/input-output-hk/plutus-apps/pull/379.
- Branch
- PR

Fix minting policy in tutorial and for state machine thread tokens

---

doc/adr/0016-cardano-node-emulator.rst
doc/adr/index.rst

This PR contains the ADR for splitting out the node emulator from plutus-contract.
The implementation is here #831
See the ADR webpage here: https://plutus-apps--835.org.readthedocs.build/en/835/adr/0016-cardano-node-emulator.html
- Branch
- PR

PLT-663 ADR for splitting out the node emulator from plutus-contact

---

plutus-contract/src/Plutus/Contract/StateMachine/OnChain.hs
plutus-ledger/src/Ledger/Tx/CardanoAPI/Internal.hs
plutus-script-utils/src/Plutus/Script/Utils/Typed.hs
plutus-script-utils/src/Plutus/Script/Utils/V1/Scripts.hs

We can avoid serialising and unserialising again to compute a hash.
The deserialisation of the script is costly too, but it's harder to avoid. We could keep both version using `These` and compute them on demand, but I'm not sure if it worth the effort.
- Branch
- PR

PLT-1205 improve the performance of `fromOnChainTx`

---

cardano-node-emulator/src/Cardano/Node/Emulator/Generators.hs
plutus-chain-index-core/changelog.d/20230103_172918_nicolas.biri_PLT_856.md
plutus-chain-index-core/src/Cardano/Protocol/Socket/Type.hs
plutus-contract/test/Spec/Emulator.hs
plutus-ledger/src/Ledger/Tx/Orphans.hs
plutus-pab-executables/changelog.d/20230103_170014_nicolas.biri_PLT_856.rst
plutus-pab-executables/plutus-pab-executables.cabal
plutus-pab-executables/tx-inject/Main.hs
plutus-pab-executables/tx-inject/TxInject/RandomTx.hs
plutus-pab/plutus-pab.cabal
plutus-pab/src/Cardano/Node/Client.hs
plutus-pab/src/Cardano/Node/Mock.hs
plutus-pab/src/Cardano/Node/Types.hs
plutus-pab/src/Cardano/Protocol/Socket/Mock/Client.hs
plutus-pab/src/Cardano/Protocol/Socket/Mock/Server.hs

I decided to keep the generation of a cardano Tx (required by `tx-inject`) out of the scope of this PR to keep an atomic change. So in `tx-inject`, we're still generating emulator tx and then creating a Cardano Tx from it when we sign it.
It could be changed if needed later in the migration.
- Branch
- PR

PLT-856 use Cardano transactions in MockNode instead of EmulatorTx

---

plutus-contract/src/Plutus/Contract/Test/Coverage/Analysis.hs
plutus-use-cases/src/Plutus/Contracts/GameStateMachine.hs
plutus-use-cases/src/Plutus/Contracts/Uniswap/OffChain.hs
plutus-use-cases/test/Spec/renderGuess.txt

This PR introduces a hack to get around the issue whereby `computeRefinedCoverageIndex` introduces spurious unreachable coverage annotations.

Fix computeRefinedCoverageIndex resulting in extra coverage annotations

---

cardano-streaming/cardano-streaming.cabal
cardano-streaming/changelog.d/20221207_115251_markus.lall_plt_171_wip.md
cardano-streaming/src/Cardano/Streaming.hs
cardano-streaming/src/Cardano/Streaming/Callbacks.hs
cardano-streaming/src/Cardano/Streaming/Helpers.hs
marconi/app/Main.hs
marconi/changelog.d/20221205_182223_markus.lall_plt_171.md
marconi/marconi.cabal
marconi/src/Marconi/CLI.hs
marconi/src/Marconi/Index/EpochStakepoolSize.hs
marconi/src/Marconi/Indexers.hs
marconi/test/EpochStakepoolSize.hs
marconi/test/Helpers.hs
marconi/test/Integration.hs
marconi/test/Spec.hs

[PLT-171: marconi indexer: stake pool delegation of a particular epoch](https://input-output.atlassian.net/browse/PLT-171)
Diff is easiest to review by looking at the separate commits as they do isolated things.
Also added a longer commit messages for the `foldBlocks` adaption commit 440ff751ab768190d71edb1465ce02ecb86540be.
Test with: `cabal run marconi-test -- -p '/prop_epoch_stakepool_size/'`
Run on testnet or mainnet:
```
CONFIG="..." # node config is required for folding over ledger states
SOCKET="..."
MAGIC='--mainnet' # or --testne-magic 2 # 2 for preprod
DB_PATH="..."
cabal run marconi:exe:marconi -- \
--disable-utxo --disable-datum --disable-script-tx \
$MAGIC \
--node-config-path "$CONFIG" \
--socket-path "$SOCKET" \
-d "$DB_PATH"
```
Depends on these PRs on cardano-node repo …

Add epoch stakepool size indexer 

---

cabal.project
nix/pkgs/haskell/sha256map.nix
plutus-contract/src/Plutus/Contract/Test/ContractModel/Interface.hs
plutus-contract/src/Plutus/Contract/Test/ContractModel/Internal.hs
plutus-script-utils/src/Plutus/Script/Utils/Typed.hs
plutus-use-cases/plutus-use-cases.cabal
plutus-use-cases/src/Plutus/Contracts/Auction.hs
plutus-use-cases/test/Spec/Auction.hs
plutus-use-cases/test/Spec/Escrow.hs
plutus-use-cases/test/Spec/GameStateMachine.hs

Updates the quickcheck-contractmodel dependency to the latest version with the new threat modelling framework.
- Reenable double satisfaction tests (this now comes with the threat modelling)
- Some simple threat model examples (GameStateMachine and Escrow)
- Use min Ada balance change logic from quickcheck-contractmodel

Threat modelling framework

---

CONTRIBUTING.adoc
shell

Several people have complained that running `nix-shell` segfaults.
We can't expect them to know the `GC_DONT_GC=1` trick.
This PR updates the CONTRIBUTING

Mention GC_DONT_GC=1 in CONTRIBUTING.adoc

---

marconi-mamba/marconi-mamba.cabal
marconi-mamba/src/Marconi/Api/Types.hs
marconi/src/Marconi/Index/Utxo.hs

Changed datum encoding in JSON-RPC from printing the ScriptData complete text in JSON to CBOR presentation
[PLT-320]
- Branch
- PR
[PLT-320]: https://input-output.atlassian.net/browse/PLT-320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix datum encoding in marconi indexer

---

plutus-contract/test/Spec/Emulator.hs

invalidScript check for a phase 2 error, something that should be catch by the validation and that does not seem to bring any value to our codebase, as it's out of the scope of our library. Removing it to save some time in the future (transition to Cardano Tx)
- Branch
- PR

remove invalidScript test

---

marconi/app/Main.hs
marconi/changelog.d/20230130_140515_konstantinos.lambrou_PLT_662_maconi_address_datum.md
marconi/marconi.cabal
marconi/src/Marconi/CLI.hs
marconi/src/Marconi/Index/AddressDatum.hs
marconi/src/Marconi/Index/ScriptTx.hs
marconi/src/Marconi/Index/Utxo.hs
marconi/src/Marconi/Indexers.hs
marconi/src/Marconi/Orphans.hs
marconi/src/Marconi/Types.hs
marconi/test/Spec.hs
marconi/test/Spec/Marconi/Index/AddressDatum.hs
marconi/test/Spec/Marconi/Index/AddressDatum/AddressDatumIndex.hs
marconi/test/Spec/Marconi/Index/AddressDatum/AddressDatumIndexEvent.hs
marconi/test/Spec/Marconi/Index/AddressDatum/Generators.hs
marconi/test/Spec/Marconi/Index/AddressDatum/Utils.hs
rewindable-index/src/RewindableIndex/Storable.hs

* Indexes all datums for a given address 
* takes about 3h starting at Alonzo era - which is the era that introduces datums
* total disk db size of ~2GB
* Supports resuming
* Does *not* include the JSON-RPC interface on top of this indexer
- Branch
- PR

PLT-662 Added Address->Datum indexer in Marconi

---

marconi-chain-index/changelog.d/20230208_200224_konstantinos.lambrou_PLT_1317_restructure_marconi_and_rewindable_index_v2.md
marconi-chain-index/marconi-chain-index.cabal
marconi-chain-index/src/Marconi/ChainIndex/Indexers/Utxo.hs
marconi-chain-index/src/Marconi/ChainIndex/Orphans.hs
marconi-mamba/README.md
marconi-mamba/app/Main.hs
marconi-mamba/changelog.d/20230208_200219_konstantinos.lambrou_PLT_1317_restructure_marconi_and_rewindable_index_v2.md
marconi-mamba/examples/json-rpc-server/src/Main.hs
marconi-mamba/examples/test-json-rpc.http
marconi-mamba/marconi-mamba.cabal
marconi-mamba/src/Marconi/Mamba/Api/HttpServer.hs
marconi-mamba/src/Marconi/Mamba/Api/Query/UtxoIndexer.hs
marconi-mamba/src/Marconi/Mamba/Api/Routes.hs
marconi-mamba/src/Marconi/Mamba/Api/Types.hs
marconi-mamba/src/Marconi/Mamba/Bootstrap.hs
marconi-mamba/test/Spec.hs
marconi-mamba/test/Spec/Marconi/Mamba/Api/Query/UtxoIndexer.hs

DRAFT, do not merge
---
Restructure and re-organize Marconi modules
- Renamed the module names from Marconi.JsonRpc to Network.JsonRpc
- Renamed `marconi` to `marconi-chain-index`
- Renamed  `rewindable-index` package to `marconi-core`  and changed
corresponding module names accordingly
- Renamed marconi-mamba module names to match those of corresponding
package name
- Branch
- PR

PLT-1317 restructure marconi-mamba

---

__std__/cells/plutus-apps/library/make-plutus-apps-project.nix
cabal.project
nix/pkgs/haskell/sha256map.nix

This change should prevent intermittent error `Condition not met by deadline: Chain not extended` and timeout of private cardano testnet.

Add activeSlotsCoeff used by plutus-e2e-tests with default value of 0.9

---

marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs
marconi-chain-index/src/Marconi/ChainIndex/Indexers/Utxo.hs
marconi-mamba/app/Main.hs
marconi-mamba/changelog.d/20230209_141628_konstantinos.lambrou_PLT_1480_make_mps_tx_indexer_queryable_through_the_json_rpc_server_of_marconi_mamba.md
marconi-mamba/db-utils/README.md
marconi-mamba/examples/json-rpc-server/src/Main.hs
marconi-mamba/marconi-mamba.cabal
marconi-mamba/src/Marconi/Mamba/Api/Query/Indexers/Utxo.hs
marconi-mamba/src/Marconi/Mamba/Api/Types.hs
marconi-mamba/src/Marconi/Mamba/Bootstrap.hs
marconi-mamba/src/Marconi/Mamba/CLI.hs
marconi-mamba/test/Spec.hs
marconi-mamba/test/Spec/Golden/Cli/marconi.help
marconi-mamba/test/Spec/Golden/Cli/marconi___addresses_to_index.help
marconi-mamba/test/Spec/Golden/Cli/marconi___help.help
marconi-mamba/test/Spec/Golden/Cli/marconi___http_port.help
marconi-mamba/test/Spec/Golden/Cli/marconi___socket.help
marconi-mamba/test/Spec/Golden/Cli/marconi___utxo_db.help
marconi-mamba/test/Spec/Marconi/Mamba/Api/Query/Indexers/Utxo.hs

* Remove the `--utxo-db` CLI parameter in favor of `--utxo-db-fname` which takes the file name instead of the full path
* Added a CLI param (`--db-dir`) for specifiying the directory in which to store the SQLite database files.
* Providing target addresses in the CLI through `--addresses-to-index` is now optional
* Querying the UTXOs for a given address does not limit the address to the
target addresses provided in the CLI.
* Fixed the resuming capability of the indexers in `marconi-mamba`
- Branch
- PR

Various small refactoring and fixes in `marconi-mamba`

---

__std__/cells/plutus-apps/packages/pre-commit-check.nix
flake.lock
flake.nix
shell.nix

Another leftover from the removal of plutus-playground

Remove references to spago from nix setup

---

plutus-e2e-tests/README.md
plutus-e2e-tests/test/Helpers.hs
plutus-e2e-tests/test/PlutusScripts.hs
plutus-e2e-tests/test/Spec/BabbageFeatures.hs
plutus-e2e-tests/test/Spec/Builtins/SECP256k1.hs

Can now run the `plutus-e2e-tests` on any cardano network by connecting to a local node instead of starting a private network. The CI will continue to run only using private testnet for now.

plutus-e2e-tests on a public network

---

marconi-chain-index/app/Main.hs
marconi-chain-index/changelog.d/20230130_134918_markus.l2ll_plt_357.md
marconi-chain-index/marconi-chain-index.cabal
marconi-chain-index/src/Marconi/ChainIndex/CLI.hs
marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs
marconi-chain-index/src/Marconi/ChainIndex/Indexers/MintBurn.hs
marconi-chain-index/src/Marconi/ChainIndex/Indexers/ScriptTx.hs
marconi-chain-index/src/Marconi/ChainIndex/Orphans.hs
marconi-chain-index/test-lib/Helpers.hs
marconi-chain-index/test/Integration.hs
marconi-chain-index/test/Spec.hs
marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/MintBurn.hs
marconi-core/src/Marconi/Core/Storable.hs
marconi/test/MintBurn.hs
marconi/test/Spec.hs

Ready for review, changes since the mob review:
- handling of intervals and a new interval test
- end-to-end test now also uses generator to create TxMintValue
I think I've also found and fixed two bugs in rewindable index:
- [4af8f94](https://github.com/input-output-hk/plutus-apps/pull/913/commits/4af8f946905c733abec642a65707a644b5900b76) `filterWithQueryInterval` wasn't using the start of interval to filter out elements
- [594f20a](https://github.com/input-output-hk/plutus-apps/pull/913/commits/594f20a57c765d4944023ea61d05215d40ae46a3) `rewind` didn't account for gaps in events
Not sure about the `filterWithQueryInterval` fix as it makes a test fail in rewindable-index: New index properties -> Insert is folding the structure.
@raduom should inspect these and perhaps add tests to for …

Add MintBurn indexer

---

marconi-mamba/marconi-mamba.cabal
marconi-mamba/src/Marconi/Mamba/Api/Query/Indexers/Utxo.hs
marconi-mamba/test/Spec/Marconi/Mamba/Api/Query/Indexers/Utxo.hs
marconi-mamba/test/Spec/Marconi/Mamba/Api/Query/Indexers/address-utxo-response.json

Users of Marconi will typically communicate with it using the JSON representation of the datatype. Thus, we need to have a golden test case which makes sure that any changes to that representation is expected and validated by PR reviewers.
- Branch
- PR

PLT-1558: Added golden test for ToJSON instance in the UTXO indexer query

---

cardano-streaming/cardano-streaming.cabal
marconi-chain-index/bench/BenchQueries.hs
marconi-chain-index/changelog.d/20230217_094612_konstantinos.lambrou_PLT_1064_create_a_benchmark_suite_in_marconi_chain_index_for_analyzing_query_response_time_of_the_address_with_the_most_utxos.md
marconi-chain-index/marconi-chain-index.cabal
marconi-chain-index/src/Marconi/ChainIndex/Indexers/AddressDatum.hs
marconi-chain-index/src/Marconi/ChainIndex/Indexers/Datum.hs
marconi-chain-index/src/Marconi/ChainIndex/Indexers/MintBurn.hs
marconi-chain-index/src/Marconi/ChainIndex/Indexers/ScriptTx.hs
marconi-chain-index/src/Marconi/ChainIndex/Indexers/Utxo.hs
marconi-chain-index/src/Marconi/ChainIndex/Orphans.hs
marconi-chain-index/test-lib/Gen/Marconi/ChainIndex/Types.hs
marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/Utxo/UtxoIndex.hs
marconi-mamba/src/Marconi/Mamba/Api/Query/Indexers/Utxo.hs

Create a simple benchmark suite in marconi-chain-index for analyzing query response time of the address with the most utxos
* Created benchmark suite in `marconi-chain-index`
* The benchmark will sync the Marconi indexer with the local node, then run the benchmark suite.
* The first benchmark implemented is the performance of the query to fetch the UTXOs of the address which has the most UTXOs.
Running `MARCONI_DB_DIRECTORY_PATH=/home/kolam/cardano-node/preprod/marconi-chain-index CARDANO_NODE_SOCKET_PATH=/home/kolam/cardano-node/preprod/cardano-node.socket cabal bench --benchmark-options '+RTS -T' marconi-chain-index`
produces the output:
```
Running 1 benchmarks...
Benchmark marconi-chain-index-bench: RUNNING...
Waiting for indexer to be fully synced...
Finished syncing!
Address …
```

PLT-1064: Create a simple benchmark suite in marconi-chain-index

---

plutus-e2e-tests/plutus-e2e-tests.cabal
plutus-e2e-tests/test/CardanoTestnet.hs

Looks like [canConnect](https://github.com/input-output-hk/hedgehog-extras/blob/9ea1845ca2036e7a1ae9fcebe393526540c5c233/src/Hedgehog/Extras/Stock/IO/Network/Socket.hs#L40) in Hedgehog.Extras had a bug so [isPortOpen](https://github.com/input-output-hk/hedgehog-extras/blob/9ea1845ca2036e7a1ae9fcebe393526540c5c233/src/Hedgehog/Extras/Stock/IO/Network/Socket.hs#L30) always reported False. Using local copy of implementation with fix for now.

Use random ports for CardanoTestnet to prevent conflict

---

marconi-chain-index/marconi-chain-index.cabal
marconi-chain-index/test-lib/Gen/Marconi/ChainIndex/Indexers/Utxo.hs
marconi-chain-index/test-lib/Helpers.hs
marconi-chain-index/test/Spec.hs
marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/EpochStakepoolSize.hs
marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/MintBurn.hs
marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/ScriptTx.hs

This PR was triggered by a `FeeTooSmallUTxO` CI error in the MintBurn test. The fix was to calculate it automatically.
In addition to the above, some more refactoring was done:
- Calculate the fee automatically for all transactions for all tests (except for the second one in ScriptTx e2e test which I couldn't figure out);
- Remove fee argument from `emptyTxBodyContent` as it's calculated automatically;
- Move tests from Integration to Spec.Marconi.ChainIndex.Indexers.ScriptTx (the integration test was mis-named, it was actually an end to end test for the ScriptTx indexer to begin with);
- Add `mkAddressValueTxOut`, a more general version of `mkAddressAdaTxOut`.
Apart from automatic fee calculation the other changes should functionally be no-ops.
All tests continue to pass.
~Question: I …

Add calculateAndUpdateTxFee

---

marconi-chain-index/changelog.d/20230222_182400_kayvan_json_rpc_test.md
marconi-chain-index/json-rpc/src/Network/JsonRpc/Client/Types.hs
marconi-chain-index/json-rpc/src/Network/JsonRpc/Types.hs
marconi-chain-index/src/Marconi/ChainIndex/Indexers/Utxo.hs
marconi-chain-index/test-lib/Gen/Marconi/ChainIndex/Indexers/Utxo.hs
marconi-chain-index/test-lib/Helpers.hs
marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/Utxo/UtxoIndex.hs
marconi-sidechain/changelog.d/20230223_182500_kayvan_json_rpc_test.md
marconi-sidechain/examples/json-rpc-client/src/Main.hs
marconi-sidechain/examples/json-rpc-server/src/Main.hs
marconi-sidechain/examples/start-json-rpc-server.sh
marconi-sidechain/marconi-sidechain.cabal
marconi-sidechain/src/Marconi/Sidechain/Api/HttpServer.hs
marconi-sidechain/src/Marconi/Sidechain/Api/Routes.hs
marconi-sidechain/src/Marconi/Sidechain/Api/Types.hs
marconi-sidechain/test/Spec/Marconi/Sidechain/Api/Query/Indexers/Utxo.hs

Create client/server servant the json-rpc test
- add a http JSON-RPC  test the RPC routes and round trip payload seiralisation
-  update the marconi-chain-index/exmples/json-rpc related modules for the recent changes
- separate the RPC routes from REST routes so that we may reuse the RPC handlers client code 
- NOTE, there is TODO that comments a failing test till we have a fix for the ScriptData round trip serialization
-
[PLT-94]
- Branch
- [x ] Tests are provided (if possible)
- [ x] Commit sequence broadly makes sense
- [x ] Key commits have useful messages
- [x ] Important changes are reflected in changelog.d of the affected packages
- PR
- [x ] Self-reviewed the diff
- [ x] Useful pull request description
- [ x] Reviewer requested
[PLT-94]: …

Utxo JSON-RPC unit tests

---

marconi-chain-index/changelog.d/20230224_061323_konstantinos.lambrou_PLT_776_fix_test_running_time_of_tx_address_to_utxo_address_test.md
marconi-chain-index/marconi-chain-index.cabal
marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs
marconi-chain-index/src/Marconi/ChainIndex/Indexers/Utxo.hs
marconi-chain-index/test-lib/Gen/Marconi/ChainIndex/Indexers/Utxo.hs
marconi-chain-index/test-lib/Gen/Marconi/ChainIndex/Mockchain.hs
marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/Utxo/UtxoIndex.hs

* Changed the `genUtxoEvent` generator so that I can also return the tx that was used to generate it
* The generated tx is customized, thus the modified property test is now a lot faster (runs under 1s)
* Fixed a bug in the datum extraction in the Utxo indexer
- Branch
- PR

PLT-776 Modified the Utxo indexer property test for testing provided target addresses

---

plutus-e2e-tests/plutus-e2e-tests.cabal
plutus-e2e-tests/test/Helpers/Utils.hs
plutus-e2e-tests/test/PlutusScripts/AlwaysSucceeds.hs
plutus-e2e-tests/test/PlutusScripts/Helpers.hs
plutus-e2e-tests/test/PlutusScripts/V1TxInfo.hs
plutus-e2e-tests/test/PlutusScripts/V2TxInfo.hs
plutus-e2e-tests/test/Spec/AlonzoFeatures.hs
plutus-e2e-tests/test/Spec/BabbageFeatures.hs
plutus-ledger/src/Ledger/Tx/CardanoAPI/Internal.hs

Same as [checkTxInfoV1Test](https://github.com/input-output-hk/plutus-apps/blob/3b16bcc141e76572917020bd154948b0b0491215/plutus-e2e-tests/test/Spec/AlonzoFeatures.hs#L47) but for Plutus version 2.
- Branch
- PR

Add V2 TXInfo test to plutus e2e tests

---

plutus-e2e-tests/README.md
plutus-e2e-tests/plutus-e2e-tests.cabal
plutus-e2e-tests/test/Helpers/Test.hs
plutus-e2e-tests/test/Helpers/Testnet.hs
plutus-e2e-tests/test/Spec.hs
plutus-e2e-tests/test/Spec/AlonzoFeatures.hs
plutus-e2e-tests/test/Spec/BabbageFeatures.hs
plutus-e2e-tests/test/Spec/Builtins/SECP256k1.hs

Rough timing comparison: local execution time is now under 2 minutes vs over 5 minutes on main.
Output now looks like:
```haskell
Running 1 test suites...
Test suite plutus-e2e-tests-test: RUNNING...
Starting local testnet in AlonzoEra PV6...
Plutus E2E Tests
Alonzo PV6 Tests:  
Running: checkTxInfoV1Test
Pass
Duration: 3.042900687000s
Running: verifySchnorrAndEcdsaTest
Pass
Duration: 0.103253914000s
OK (18.42s)
✓ <interactive> passed 1 test.
Babbage PV7 Tests: 
Starting local testnet in BabbageEra PV7...
Running: checkTxInfoV1Test
Pass
Duration: 3.045092866000s
Running: checkTxInfoV2Test
Pass
Duration: 2.053581889000s
Running: verifySchnorrAndEcdsaTest
Pass
Duration: 0.096159726000s
Running: referenceScriptMintTest
Pass
Duration: 3.378465432000s
Running: …
```

E2E tests share testnet instances

---

cardano-streaming/src/Cardano/Streaming.hs
marconi-chain-index/app/Main.hs
marconi-chain-index/marconi-chain-index.cabal
marconi-chain-index/performance/monitor-marconi-sync-all.sh
marconi-chain-index/performance/monitor-marconi-sync.sh
marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs
marconi-chain-index/src/Marconi/ChainIndex/Indexers/EpochStakepoolSize.hs
marconi-chain-index/src/Marconi/ChainIndex/Indexers/Utxo.hs
marconi-chain-index/src/Marconi/ChainIndex/Node/Client/GenesisConfig.hs
marconi-chain-index/src/Marconi/ChainIndex/Orphans.hs
marconi-chain-index/src/Marconi/ChainIndex/Utils.hs
marconi-chain-index/test-lib/Gen/Marconi/ChainIndex/Types.hs
marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/EpochStakepoolSize.hs
marconi-chain-index/test/Spec/Marconi/ChainIndex/Orphans.hs

* Rewrote the Epoch-StakePoolDelegation using the marconi-core interface and to make it support rollbacks and resuming.
* Computed the LedgerState directly with functions in `ouroboros-network` instead of using `cardano-api` and `cardano-streaming` (allows more fined grained control of what to extract).
* Moved orphan instances of EpochStakepoolSize indexer to the Orphans module and added rountrip ToField/FromField tests.
* Added LedgerState serialization/deserialization functions in Orphans module.
IMPORTANT NOTE: 
Not very performant, but not clear on how to make it better. The use of `LedgerState` uses lots of memory. Could not fully sync on my machine as I don't have enough memory (32GB). The node by itself uses about 12GB. I have 6GB for other processes. Then, I only managed to sync …

PLT-214 Refactored the Epoch-StakePoolDelegation indexer to the Marconi interface.

---

marconi-chain-index/src/Marconi/ChainIndex/Indexers/EpochStakepoolSize.hs
marconi-sidechain/README.md
marconi-sidechain/app/Main.hs
marconi-sidechain/examples/json-rpc-server/src/Main.hs
marconi-sidechain/marconi-sidechain.cabal
marconi-sidechain/src/Marconi/Sidechain/Api/HttpServer.hs
marconi-sidechain/src/Marconi/Sidechain/Api/Query/Indexers/EpochSPD.hs
marconi-sidechain/src/Marconi/Sidechain/Api/Query/Indexers/Utxo.hs
marconi-sidechain/src/Marconi/Sidechain/Api/Routes.hs
marconi-sidechain/src/Marconi/Sidechain/Api/Types.hs
marconi-sidechain/src/Marconi/Sidechain/Bootstrap.hs
marconi-sidechain/src/Marconi/Sidechain/CLI.hs
marconi-sidechain/src/Marconi/Sidechain/Utils.hs
marconi-sidechain/test/Spec.hs
marconi-sidechain/test/Spec/Golden/Cli/marconi-sidechain___help.help
marconi-sidechain/test/Spec/Golden/Cli/marconi-sidechain___socket.help
marconi-sidechain/test/Spec/Marconi/Sidechain/Api/Query/Indexers/Utxo.hs
marconi-sidechain/test/Spec/Marconi/Sidechain/Api/Routes/Golden/epoch-stakepooldelegation-response.json
marconi-sidechain/test/Spec/Marconi/Sidechain/Routes.hs

Add JSON-RPC querying of the stake pool delegation (SPD) by epoch in `marconi-sidechain`.
* Add indexing and JSON-RPC querying of the SPD by epoch in `marconi-sidechain`.
* Added golden test for JSON response of stake pool delegation by epoch
* Fixed resuming of Utxo indexer to include *all* possible chain points, not only the latest ones.
* Updated README of `marconi-sidechain` to include an example of request and response for the JSON-RPC server on that specific endpoint.
- Branch
- PR

PLT-1311 Add JSON-RPC querying of the stake pool delegation (SPD) by epoch in `marconi-sidechain`.

---

__std__/cells/plutus-apps/devshells/plutus-apps-shell.nix
marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs
marconi-chain-index/src/Marconi/ChainIndex/Indexers/Utxo.hs
marconi-chain-index/src/Marconi/ChainIndex/Orphans.hs
marconi-chain-index/test-lib/Gen/Marconi/ChainIndex/Indexers/Utxo.hs
marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/Utxo/UtxoIndex.hs
marconi-sidechain/db-utils/exe/Main.hs
marconi-sidechain/examples/json-rpc-server/src/Main.hs
marconi-sidechain/examples/start-json-rpc-server.sh
marconi-sidechain/examples/test-json-rpc.http
marconi-sidechain/test/Spec/Marconi/Sidechain/Api/Query/Indexers/Utxo.hs
plutus-chain-index-core/src/Plutus/ChainIndex/Marconi.hs
plutus-chain-index-core/test/Plutus/ChainIndex/MarconiSpec.hs

Fixes are:
- fix the broken property tests in Utxo
- remove the `equivalent` test criteria, replace with sort/compare
- add `isToVacuume` switch indicating SQLite vacuum operation. The switch is not in CLI, and set to True. In test we set that to False.
- fix the Query results
-  Balance the in-memory Utxos in regards to `Spent`
- minor change in the JSON form of the UtxoResponse. 
Regression test showing the failure see [PR-1032](https://github.com/input-output-hk/plutus-apps/pull/1032)
- Branch
- PR

Fix utxo query result and test cases, PLT-1540, and PLT-1536

---

marconi-chain-index/marconi-chain-index.cabal
marconi-chain-index/src/Marconi/ChainIndex/Indexers/MintBurn.hs
marconi-chain-index/test-lib/Marconi/ChainIndex/TestLib/StorableProperties.hs
marconi-chain-index/test/Spec.hs
marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/AddressDatum/AddressDatumIndex.hs
marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/MintBurn.hs
marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/Utxo/UtxoIndex.hs

* Fixed a syntax error of the `getStoredEvents` SQL query.
* Fixed the `getStoredEvents` SQL query so that the points returned are in descending order.
* Added a property test which verifies that the ChainPointAtGenesis is always returned by `resumablePoints`.
* Added a property test which verifies that the points returned by `resumablePoints` are sorted in descending order.
- Branch
- PR

PLT-5459 Fix resuming on the MintBurn indexer

---

cardano-node-emulator/cardano-node-emulator.cabal
plutus-contract/plutus-contract.cabal

This PR is response to Slack conversation on [#cardano-dev channel](https://input-output-rnd.slack.com/archives/CCZSDE005/p1679613693027109) in regards to upgrading aeson to 2.0 or better.
Note that plutus-apps cabal.project is configured for 2.0  and this change is more for readability.
[PLT-5442](https://input-output.atlassian.net/browse/PLT-5442)
- Branch
- PR
[PLT-5442]: https://input-output.atlassian.net/browse/PLT-5442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Restrict to aeson 2.0 or better

---

__std__/cells/automation/hydra-jobs.nix

Remove the `combined-plutus-apps-haddock` in darwin CI jobs, but still keep it in the linux CI jobs. It often gets timed out in darwin because of how large this job is. Plus, it's not really necessary to check this in darwin (linux suffices).
- Branch
- PR

Deactive combined-haddock CI job in darwin

---

.github/workflows/haddock.yml
CONTRIBUTING.adoc
flake.lock
flake.nix
nix/shell.nix

Instructions on how to install & upgrade nix and how to setup the binary caches are now included in the [relevant section](https://github.com/input-output-hk/iogx/blob/main/doc/api.md#flakenix) of the IOGX manual. 
This PR updates the relevant sections of the README/CONTRIBUTING/RELEASE documents.

Update nix documentation in CONTRIBUTING.adoc and RELEASE.adoc
